# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the anim domain."""

from ..session import _drop_none


def delete_keyframe(_session, *, object=None, data_path=None, frame=None, index=None):
    """Delete a keyframe on an object property at a frame

    Parameters (omit to use the server default):
    object: Object to edit (defaults to active)
    data_path: Property path, e.g. 'location'
    frame: Frame to delete (defaults to current scene frame)
    index: Array element index (-1 deletes all components); server default: -1
    """
    _payload = {"object": object, "data_path": data_path, "frame": frame, "index": index}
    return _session.call("anim.delete_keyframe", _drop_none(_payload))


def insert_keyframe(_session, *, object=None, data_path=None, frame=None, index=None):
    """Insert a keyframe on an object property at a frame

    Parameters (omit to use the server default):
    object: Object to key (defaults to active)
    data_path: Property path, e.g. 'location' or 'rotation_euler'
    frame: Frame to key (defaults to current scene frame)
    index: Array element index to key (-1 keys all components); server default: -1
    """
    _payload = {"object": object, "data_path": data_path, "frame": frame, "index": index}
    return _session.call("anim.insert_keyframe", _drop_none(_payload))


def keyframes(_session, *, object=None):
    """Detailed f-curve and keyframe report for an object

    Parameters (omit to use the server default):
    object: Object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("anim.keyframes", _drop_none(_payload))


def list_actions(_session):
    """List the actions in the file (read-only)
    """
    return _session.call("anim.list_actions", {})


def report(_session, *, object=None):
    """Animation report for an object: frame range, f-curve count (read-only)

    Parameters (omit to use the server default):
    object: Object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("anim.report", _drop_none(_payload))


def set_frame(_session, *, frame=None):
    """Set the current scene frame (playhead)

    Parameters (omit to use the server default):
    frame: Frame number to set as current
    """
    _payload = {"frame": frame}
    return _session.call("anim.set_frame", _drop_none(_payload))


def set_interpolation(_session, *, object=None, interpolation=None):
    """Set interpolation for all keyframes on an object's f-curves

    Parameters (omit to use the server default):
    object: Object whose f-curves to edit (defaults to active)
    interpolation: Interpolation mode applied to every keyframe point
    """
    _payload = {"object": object, "interpolation": interpolation}
    return _session.call("anim.set_interpolation", _drop_none(_payload))


def set_timeline(_session, *, frame_current=None, frame_start=None, frame_end=None, fps=None):
    """Set scene timeline range, current frame, and frame rate

    Parameters (omit to use the server default):
    frame_current: Current playhead frame to set
    frame_start: Scene start frame to set
    frame_end: Scene end frame to set
    fps: Render frame rate to set
    """
    _payload = {"frame_current": frame_current, "frame_start": frame_start, "frame_end": frame_end, "fps": fps}
    return _session.call("anim.set_timeline", _drop_none(_payload))


def timeline(_session):
    """Report scene timeline range, current frame, and frame rate
    """
    return _session.call("anim.timeline", {})
