# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the api domain."""

from ..session import _drop_none


def report(_session):
    """Report live Blender API operator/type metadata surface
    """
    return _session.call("api.report", {})


def search(_session, *, query=None, limit=None):
    """Search live Blender API operators and RNA types

    Parameters (omit to use the server default):
    query: Search query; server default: ''
    limit: Maximum results to return; server default: 20
    """
    _payload = {"query": query, "limit": limit}
    return _session.call("api.search", _drop_none(_payload))
