# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the app domain."""

from ..session import _drop_none


def addon_disable(_session, *, module=None):
    """Disable an installed Blender add-on module

    Parameters (omit to use the server default):
    module: Add-on module id
    """
    _payload = {"module": module}
    return _session.call("app.addon_disable", _drop_none(_payload))


def addon_enable(_session, *, module=None):
    """Enable an installed Blender add-on module

    Parameters (omit to use the server default):
    module: Add-on module id
    """
    _payload = {"module": module}
    return _session.call("app.addon_enable", _drop_none(_payload))


def addons(_session):
    """List available Blender add-ons with enabled and loaded state
    """
    return _session.call("app.addons", {})


def file_new(_session, *, force=None):
    """Start a new empty file; force is required if current file is dirty

    Parameters (omit to use the server default):
    force: Discard unsaved changes; server default: False
    """
    _payload = {"force": force}
    return _session.call("app.file_new", _drop_none(_payload))


def file_open(_session, *, path=None, force=None):
    """Open an existing .blend file by absolute path; force is required if current file is dirty

    Parameters (omit to use the server default):
    path: Absolute path to .blend file
    force: Discard unsaved changes; server default: False
    """
    _payload = {"path": path, "force": force}
    return _session.call("app.file_open", _drop_none(_payload))


def file_revert(_session, *, force=None):
    """Reload the current file from disk; force is always required

    Parameters (omit to use the server default):
    force: Confirm reload from disk; server default: False
    """
    _payload = {"force": force}
    return _session.call("app.file_revert", _drop_none(_payload))


def file_save(_session, *, path=None):
    """Save the current file, or save to an absolute path if the file is unsaved

    Parameters (omit to use the server default):
    path: Absolute path used when saving an unsaved file
    """
    _payload = {"path": path}
    return _session.call("app.file_save", _drop_none(_payload))


def file_save_as(_session, *, path=None):
    """Save the current file to a new absolute path and make it active

    Parameters (omit to use the server default):
    path: Absolute output .blend path
    """
    _payload = {"path": path}
    return _session.call("app.file_save_as", _drop_none(_payload))


def file_save_copy(_session, *, path=None):
    """Save a copy of the current file without changing the active file path

    Parameters (omit to use the server default):
    path: Absolute output .blend path
    """
    _payload = {"path": path}
    return _session.call("app.file_save_copy", _drop_none(_payload))


def info(_session):
    """Report Blender runtime, active file, dirty state, scene, workspace, and render engine
    """
    return _session.call("app.info", {})


def preferences_save(_session):
    """Save current Blender user preferences
    """
    return _session.call("app.preferences_save", {})


def preferences_summary(_session):
    """Report safe high-level user preference values
    """
    return _session.call("app.preferences_summary", {})


def redo(_session):
    """Run Blender redo for the active session
    """
    return _session.call("app.redo", {})


def undo(_session):
    """Run Blender undo for the active session
    """
    return _session.call("app.undo", {})


def workspace_set(_session, *, name=None):
    """Switch the active window to a named workspace

    Parameters (omit to use the server default):
    name: Workspace name
    """
    _payload = {"name": name}
    return _session.call("app.workspace_set", _drop_none(_payload))


def workspaces(_session):
    """List workspaces and report the active workspace
    """
    return _session.call("app.workspaces", {})
