# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the asset_class domain."""

from ..session import _drop_none


def describe(_session, *, asset_class=None):
    """Describe one Layer 2 game-asset class profile

    Parameters (omit to use the server default):
    asset_class: Asset class profile id
    """
    _payload = {"asset_class": asset_class}
    return _session.call("asset_class.describe", _drop_none(_payload))


def list(_session):
    """List Layer 2 game-asset class profiles
    """
    return _session.call("asset_class.list", {})
