# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the camera domain."""

from ..session import _drop_none


def create(_session, *, name=None, location=None, rotation=None, lens=None, type=None, ortho_scale=None, clip_start=None, clip_end=None, active=None):
    """Create a camera and optionally make it the active scene camera

    Parameters (omit to use the server default):
    name: Optional camera object name; server default: ''
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    lens: Perspective focal length in mm; server default: 50.0
    type: Camera projection type; server default: 'PERSP'
    ortho_scale: Orthographic camera scale; server default: 6.0
    clip_start: Near clipping distance; server default: 0.1
    clip_end: Far clipping distance; server default: 1000.0
    active: Make this the active scene camera; server default: True
    """
    _payload = {"name": name, "location": location, "rotation": rotation, "lens": lens, "type": type, "ortho_scale": ortho_scale, "clip_start": clip_start, "clip_end": clip_end, "active": active}
    return _session.call("camera.create", _drop_none(_payload))


def list(_session):
    """List scene cameras and active camera
    """
    return _session.call("camera.list", {})


def report(_session, *, camera=None):
    """Report one camera, defaulting to the active scene camera

    Parameters (omit to use the server default):
    camera: Camera object name; server default: ''
    """
    _payload = {"camera": camera}
    return _session.call("camera.report", _drop_none(_payload))


def set(_session, *, camera=None, lens=None, type=None, ortho_scale=None, clip_start=None, clip_end=None):
    """Set common camera data properties

    Parameters (omit to use the server default):
    camera: Camera object name
    lens: Perspective focal length in mm
    type: Camera projection type
    ortho_scale: Orthographic camera scale
    clip_start: Near clipping distance
    clip_end: Far clipping distance
    """
    _payload = {"camera": camera, "lens": lens, "type": type, "ortho_scale": ortho_scale, "clip_start": clip_start, "clip_end": clip_end}
    return _session.call("camera.set", _drop_none(_payload))


def set_active(_session, *, camera=None):
    """Set the active scene camera

    Parameters (omit to use the server default):
    camera: Camera object name
    """
    _payload = {"camera": camera}
    return _session.call("camera.set_active", _drop_none(_payload))
