# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the capabilities domain."""

from ..session import _drop_none


def describe(_session, *, id=None):
    """Get the full typed parameter schema for one operation before calling it

    Parameters (omit to use the server default):
    id: Operator id, e.g. 'mesh.bevel'
    """
    _payload = {"id": id}
    return _session.call("capabilities.describe", _drop_none(_payload))


def domains(_session):
    """List the craft domains and how many operations each exposes
    """
    return _session.call("capabilities.domains", {})


def invoke(_session, *, idname=None, args=None, object=None, mode=None, select=None):
    """Run any Blender operator with args validated against its schema (undo-safe)

    Parameters (omit to use the server default):
    idname: Operator id, e.g. 'mesh.bevel'
    args: Args as a JSON object string, e.g. '{"offset": 0.2}'
    object: Active object name to set before running (optional)
    mode: Interaction mode, e.g. 'EDIT' / 'OBJECT' (optional)
    select: Object names to select as a JSON array string, e.g. '["Cube"]'
    """
    _payload = {"idname": idname, "args": args, "object": object, "mode": mode, "select": select}
    return _session.call("capabilities.invoke", _drop_none(_payload))


def search(_session, *, query=None, kind=None, domain=None, limit=None):
    """Search ALL of Blender for a capability by keyword, ranked (start here)

    Parameters (omit to use the server default):
    query: What you want to do, e.g. 'bevel', 'unwrap', 'smooth'
    kind: Restrict to operators, types, or both; server default: 'any'
    domain: Optional craft domain/category to scope to, e.g. 'mesh', 'uv'
    limit: Max matches; server default: 30
    """
    _payload = {"query": query, "kind": kind, "domain": domain, "limit": limit}
    return _session.call("capabilities.search", _drop_none(_payload))


def tools(_session, *, domain=None, name=None):
    """Navigate THIS server's tools: no args -> domain map; {domain} -> its tools; {name} -> one schema

    Parameters (omit to use the server default):
    domain: Craft domain from the no-args map, e.g. 'mesh', 'uv'
    name: Exact tool name for a full input schema, e.g. 'scene.create_object'
    """
    _payload = {"domain": domain, "name": name}
    return _session.call("capabilities.tools", _drop_none(_payload))
