# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the compositor domain."""

from ..session import _drop_none


def add_node(_session, *, type=None, name=None):
    """Add a node to the scene compositor node tree

    Parameters (omit to use the server default):
    type: Compositor node bl_idname, e.g. CompositorNodeBlur
    name: Optional node name; server default: ''
    """
    _payload = {"type": type, "name": name}
    return _session.call("compositor.add_node", _drop_none(_payload))


def enable(_session, *, enable=None):
    """Enable or disable scene compositor nodes

    Parameters (omit to use the server default):
    enable: Whether compositor nodes should be enabled; server default: True
    """
    _payload = {"enable": enable}
    return _session.call("compositor.enable", _drop_none(_payload))


def link(_session, *, from_node=None, from_socket=None, to_node=None, to_socket=None):
    """Link two compositor node sockets

    Parameters (omit to use the server default):
    from_node: Source node name
    from_socket: Source output socket name or index
    to_node: Destination node name
    to_socket: Destination input socket name or index
    """
    _payload = {"from_node": from_node, "from_socket": from_socket, "to_node": to_node, "to_socket": to_socket}
    return _session.call("compositor.link", _drop_none(_payload))


def report(_session):
    """Report scene compositor node tree
    """
    return _session.call("compositor.report", {})
