# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the constraints domain."""

from ..session import _drop_none


def add(_session, *, object=None, type=None, name=None, owner=None, bone=None):
    """Add an object or pose-bone constraint

    Parameters (omit to use the server default):
    object: Object owning the constraint stack
    type: Blender constraint type, e.g. COPY_LOCATION or IK
    name: Optional constraint name; server default: ''
    owner: Constraint owner stack; server default: 'OBJECT'
    bone: Pose bone name when owner is BONE; server default: ''
    """
    _payload = {"object": object, "type": type, "name": name, "owner": owner, "bone": bone}
    return _session.call("constraints.add", _drop_none(_payload))


def list(_session, *, object=None, owner=None, bone=None):
    """List object or pose-bone constraints

    Parameters (omit to use the server default):
    object: Object owning the constraint stack
    owner: Constraint owner stack; server default: 'OBJECT'
    bone: Pose bone name when owner is BONE; server default: ''
    """
    _payload = {"object": object, "owner": owner, "bone": bone}
    return _session.call("constraints.list", _drop_none(_payload))


def remove(_session, *, object=None, name=None, owner=None, bone=None):
    """Remove a named object or pose-bone constraint

    Parameters (omit to use the server default):
    object: Object owning the constraint stack
    name: Constraint name to remove
    owner: Constraint owner stack; server default: 'OBJECT'
    bone: Pose bone name when owner is BONE; server default: ''
    """
    _payload = {"object": object, "name": name, "owner": owner, "bone": bone}
    return _session.call("constraints.remove", _drop_none(_payload))


def report(_session, *, object=None, name=None, owner=None, bone=None):
    """Report live RNA properties for object or pose-bone constraints

    Parameters (omit to use the server default):
    object: Object owning the constraint stack
    name: Optional constraint name; omit for all; server default: ''
    owner: Constraint owner stack; server default: 'OBJECT'
    bone: Pose bone name when owner is BONE; server default: ''
    """
    _payload = {"object": object, "name": name, "owner": owner, "bone": bone}
    return _session.call("constraints.report", _drop_none(_payload))


def set(_session, *, object=None, name=None, property=None, value=None, owner=None, bone=None):
    """Set one RNA property on an object or pose-bone constraint

    Parameters (omit to use the server default):
    object: Object owning the constraint stack
    name: Constraint name to edit
    property: Constraint RNA property identifier
    value: New value as JSON, e.g. 0.5, false, or {"object":"Cube"}
    owner: Constraint owner stack; server default: 'OBJECT'
    bone: Pose bone name when owner is BONE; server default: ''
    """
    _payload = {"object": object, "name": name, "property": property, "value": value, "owner": owner, "bone": bone}
    return _session.call("constraints.set", _drop_none(_payload))
