# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the context domain."""

from ..session import _drop_none


def areas(_session):
    """List available editor areas for context overrides
    """
    return _session.call("context.areas", {})


def info(_session):
    """Report active object, selected objects, mode, mesh select mode, and available areas
    """
    return _session.call("context.info", {})


def mesh_select_mode(_session, *, mode=None):
    """Set mesh edit selection mode

    Parameters (omit to use the server default):
    mode: Mesh select mode
    """
    _payload = {"mode": mode}
    return _session.call("context.mesh_select_mode", _drop_none(_payload))


def mode_set(_session, *, mode=None, object=None, select=None):
    """Switch Blender interaction mode, optionally activating an object first

    Parameters (omit to use the server default):
    mode: Interaction mode
    object: Optional object to make active first; server default: ''
    select: Select the object before switching mode; server default: True
    """
    _payload = {"mode": mode, "object": object, "select": select}
    return _session.call("context.mode_set", _drop_none(_payload))


def poll_operator(_session, *, idname=None, object=None, mode=None, select=None):
    """Check whether a Blender operator polls in the current or proposed context

    Parameters (omit to use the server default):
    idname: Operator id, e.g. mesh.subdivide
    object: Optional active object for the poll; server default: ''
    mode: Optional mode for the poll; server default: ''
    select: Optional comma-separated selected objects; server default: ''
    """
    _payload = {"idname": idname, "object": object, "mode": mode, "select": select}
    return _session.call("context.poll_operator", _drop_none(_payload))


def select_all(_session, *, action=None):
    """Select, deselect, or invert selection for all scene objects

    Parameters (omit to use the server default):
    action: Selection action applied to every scene object; server default: 'DESELECT'
    """
    _payload = {"action": action}
    return _session.call("context.select_all", _drop_none(_payload))


def select_objects(_session, *, objects=None, action=None, active=None):
    """Update object selection by comma-separated object names

    Parameters (omit to use the server default):
    objects: Comma-separated object names
    action: How the named objects combine with the current selection; server default: 'REPLACE'
    active: Optional active object after selection; server default: ''
    """
    _payload = {"objects": objects, "action": action, "active": active}
    return _session.call("context.select_objects", _drop_none(_payload))


def set_active(_session, *, object=None, select=None):
    """Set the active object and optionally select it

    Parameters (omit to use the server default):
    object: Object to make active
    select: Also select the object; server default: True
    """
    _payload = {"object": object, "select": select}
    return _session.call("context.set_active", _drop_none(_payload))
