# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the feedback domain."""

from ..session import _drop_none


def capture(_session, *, object=None, view=None, shading=None, res=None):
    """Render one view (named or the live scene camera) to a PNG the agent can see

    Parameters (omit to use the server default):
    object: Object to frame; whole scene if omitted
    view: Named view or 'current' scene camera; server default: 'current'
    shading: SOLID/WIREFRAME (workbench) or MATERIAL/RENDERED (EEVEE); server default: 'SOLID'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "view": view, "shading": shading, "res": res}
    return _session.call("feedback.capture", _drop_none(_payload))


def capture_intake(_session, *, object=None):
    """Record the do-no-harm baseline: fixed-frame ortho alpha silhouettes + bbox + a session checkpoint

    Parameters (omit to use the server default):
    object: Mesh object to baseline (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("feedback.capture_intake", _drop_none(_payload))


def capture_views(_session, *, object=None, preset=None, shading=None, res=None):
    """Render a multi-angle preset (the anti-blob) as several images

    Parameters (omit to use the server default):
    object: Object to frame; whole scene if omitted
    preset: ortho4=[front,right,top,persp], ortho6=six axes, orbit4=4 orbit angles; server default: 'ortho4'
    shading: Workbench (SOLID/WIREFRAME) or EEVEE (MATERIAL/RENDERED); server default: 'SOLID'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "preset": preset, "shading": shading, "res": res}
    return _session.call("feedback.capture_views", _drop_none(_payload))


def critique(_session, *, object=None, preset=None, shading=None, res=None):
    """One observe call to judge a model: multi-angle images + mesh/UV report bundled

    Parameters (omit to use the server default):
    object: Object to judge; whole scene if omitted
    preset: Multi-angle preset for the images (the anti-blob); server default: 'ortho4'
    shading: Workbench (SOLID/WIREFRAME) or EEVEE (MATERIAL/RENDERED); server default: 'SOLID'
    res: Square render resolution (px); server default: 640
    """
    _payload = {"object": object, "preset": preset, "shading": shading, "res": res}
    return _session.call("feedback.critique", _drop_none(_payload))


def lookdev(_session, *, object=None, count=None, res=None):
    """Render a material-shaded lookdev turntable and return quality analytics

    Parameters (omit to use the server default):
    object: Mesh to inspect (defaults to active)
    count: Number of turntable frames; server default: 6
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "count": count, "res": res}
    return _session.call("feedback.lookdev", _drop_none(_payload))


def orientation(_session, *, object=None, view=None, res=None):
    """Render a normal/backface orientation eye and return orientation analytics

    Parameters (omit to use the server default):
    object: Mesh to inspect (defaults to active)
    view: Named view to render from; server default: 'persp'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "view": view, "res": res}
    return _session.call("feedback.orientation", _drop_none(_payload))


def preservation(_session, *, object=None):
    """Do-no-harm metric: mean/min silhouette IoU of current form vs the stored intake baseline + bbox delta (read-only, no revert)

    Parameters (omit to use the server default):
    object: Object with a stored intake baseline (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("feedback.preservation", _drop_none(_payload))


def quality(_session, *, object=None, asset_class=None, triangle_budget=None, material_budget=None, texture_budget=None, min_lods=None, max_lod_triangle_ratio=None, max_lod_bounds_delta=None, min_collision_hulls=None, max_collision_oversize_ratio=None, max_texture_size=None, export_profile=None, export_format=None, export_y_up=None, allowed_formats=None, require_collision=None, require_applied_transforms=None, name_regex=None):
    """Objective quality metrics for a mesh: topology, UVs, orientation, symmetry, proportion, scale, engine/material readiness (read-only)

    Parameters (omit to use the server default):
    object: Mesh object to measure (defaults to active)
    asset_class: Layer 2 asset-class profile
    triangle_budget: Maximum triangles for the optimize gate
    material_budget: Maximum material slots for the optimize gate
    texture_budget: Maximum unique image textures for the optimize gate
    min_lods: Minimum detected LOD variants for the optimize gate
    max_lod_triangle_ratio: Maximum allowed triangle ratio for each LOD relative to the source
    max_lod_bounds_delta: Maximum relative bounds delta allowed for LOD silhouette preservation
    min_collision_hulls: Minimum detected collision hull count
    max_collision_oversize_ratio: Maximum collision union oversize ratio relative to the source bounds
    max_texture_size: Maximum texture dimension for material atlas readiness
    export_profile: Export profile: GENERIC, GODOT, UNREAL, or CUSTOM; server default: 'GENERIC'
    export_format: Planned export format for profile validation; server default: 'GLB'
    export_y_up: Planned +Y-up export option for profile validation
    allowed_formats: CUSTOM export profile allowed formats; server default: ''
    require_collision: CUSTOM export profile collision-proxy requirement
    require_applied_transforms: CUSTOM export profile applied-transform requirement
    name_regex: CUSTOM export profile object-name regex; server default: ''
    """
    _payload = {"object": object, "asset_class": asset_class, "triangle_budget": triangle_budget, "material_budget": material_budget, "texture_budget": texture_budget, "min_lods": min_lods, "max_lod_triangle_ratio": max_lod_triangle_ratio, "max_lod_bounds_delta": max_lod_bounds_delta, "min_collision_hulls": min_collision_hulls, "max_collision_oversize_ratio": max_collision_oversize_ratio, "max_texture_size": max_texture_size, "export_profile": export_profile, "export_format": export_format, "export_y_up": export_y_up, "allowed_formats": allowed_formats, "require_collision": require_collision, "require_applied_transforms": require_applied_transforms, "name_regex": name_regex}
    return _session.call("feedback.quality", _drop_none(_payload))


def readiness(_session, *, object=None, asset_class=None):
    """Objective game-ready scorecard: fraction of all objective gates passed, order-free + deduped (no judge, no images)

    Parameters (omit to use the server default):
    object: Mesh object to score (defaults to active)
    asset_class: Layer 2 asset-class profile
    """
    _payload = {"object": object, "asset_class": asset_class}
    return _session.call("feedback.readiness", _drop_none(_payload))


def silhouette(_session, *, object=None, preset=None, res=None):
    """Flat silhouette from preset angles + proportion/symmetry — the form eye.

    Parameters (omit to use the server default):
    object: Object to frame; defaults to active
    preset: ortho4=[front,right,top,persp], ortho6=six axes, orbit4=4 orbit angles; server default: 'ortho4'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "preset": preset, "res": res}
    return _session.call("feedback.silhouette", _drop_none(_payload))


def topology(_session, *, object=None, view=None, res=None):
    """Render a topology overlay: n-gons red, tris orange, quads grey, plus wireframe

    Parameters (omit to use the server default):
    object: Mesh to inspect (defaults to active)
    view: Named view to render from; server default: 'persp'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "view": view, "res": res}
    return _session.call("feedback.topology", _drop_none(_payload))


def turntable(_session, *, object=None, count=None, shading=None, res=None):
    """Orbit the object/scene and return a sequence of images

    Parameters (omit to use the server default):
    object: Object to orbit; whole scene if omitted
    count: Number of evenly-spaced orbit frames; server default: 6
    shading: Workbench (SOLID/WIREFRAME) or EEVEE (MATERIAL/RENDERED); server default: 'SOLID'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "count": count, "shading": shading, "res": res}
    return _session.call("feedback.turntable", _drop_none(_payload))


def uv(_session, *, object=None, view=None, res=None, texture_size=None):
    """Render a UV checker eye and return structured UV analytics

    Parameters (omit to use the server default):
    object: Mesh to inspect (defaults to active)
    view: Named view to render from; server default: 'persp'
    res: Square render resolution (px); server default: 768
    texture_size: Reference texture size for UV analytics; server default: 1024
    """
    _payload = {"object": object, "view": view, "res": res, "texture_size": texture_size}
    return _session.call("feedback.uv", _drop_none(_payload))


def wire_shaded(_session, *, object=None, view=None, res=None):
    """Render shaded material view with real wire geometry overlay and quality analytics

    Parameters (omit to use the server default):
    object: Mesh to inspect (defaults to active)
    view: Named view to render from; server default: 'persp'
    res: Square render resolution (px); server default: 768
    """
    _payload = {"object": object, "view": view, "res": res}
    return _session.call("feedback.wire_shaded", _drop_none(_payload))
