# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the geometry_nodes domain."""

from ..session import _drop_none


def add_node(_session, *, object=None, modifier=None, type=None, name=None):
    """Add a node to a Geometry Nodes modifier group

    Parameters (omit to use the server default):
    object: Object owning the Geometry Nodes modifier
    modifier: Modifier name; defaults to first Geometry Nodes modifier; server default: ''
    type: Node bl_idname, e.g. GeometryNodeTransform
    name: Optional node name; server default: ''
    """
    _payload = {"object": object, "modifier": modifier, "type": type, "name": name}
    return _session.call("geometry_nodes.add_node", _drop_none(_payload))


def create_modifier(_session, *, object=None, name=None):
    """Create a Geometry Nodes modifier with Blender's default node group

    Parameters (omit to use the server default):
    object: Object receiving the Geometry Nodes modifier
    name: Optional modifier name; server default: ''
    """
    _payload = {"object": object, "name": name}
    return _session.call("geometry_nodes.create_modifier", _drop_none(_payload))


def link(_session, *, object=None, modifier=None, from_node=None, from_socket=None, to_node=None, to_socket=None):
    """Create a link between two Geometry Nodes sockets

    Parameters (omit to use the server default):
    object: Object owning the Geometry Nodes modifier
    modifier: Modifier name; defaults to first Geometry Nodes modifier; server default: ''
    from_node: Source node name
    from_socket: Source output socket name or index
    to_node: Destination node name
    to_socket: Destination input socket name or index
    """
    _payload = {"object": object, "modifier": modifier, "from_node": from_node, "from_socket": from_socket, "to_node": to_node, "to_socket": to_socket}
    return _session.call("geometry_nodes.link", _drop_none(_payload))


def report(_session, *, object=None, modifier=None):
    """Report a Geometry Nodes modifier and its node group

    Parameters (omit to use the server default):
    object: Object owning the Geometry Nodes modifier
    modifier: Modifier name; defaults to first Geometry Nodes modifier; server default: ''
    """
    _payload = {"object": object, "modifier": modifier}
    return _session.call("geometry_nodes.report", _drop_none(_payload))
