# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the geometry domain."""

from ..session import _drop_none


def convert_to_mesh(_session, *, object=None, name=None, keep_original=None):
    """Convert a non-mesh geometry object to a mesh

    Parameters (omit to use the server default):
    object: Object name
    name: Optional converted mesh name; server default: ''
    keep_original: Keep the source object and create a mesh copy; server default: False
    """
    _payload = {"object": object, "name": name, "keep_original": keep_original}
    return _session.call("geometry.convert_to_mesh", _drop_none(_payload))


def create_curve(_session, *, type=None, name=None, radius=None, location=None, rotation=None, scale=None):
    """Create a curve primitive

    Parameters (omit to use the server default):
    type: Curve primitive type
    name: Optional object name; server default: ''
    radius: Primitive radius; server default: 1.0
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    """
    _payload = {"type": type, "name": name, "radius": radius, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("geometry.create_curve", _drop_none(_payload))


def create_grease_pencil(_session, *, type=None, name=None, radius=None, use_in_front=None, location=None, rotation=None, scale=None):
    """Create a grease pencil object

    Parameters (omit to use the server default):
    type: Grease pencil object type; server default: 'EMPTY'
    name: Optional object name; server default: ''
    radius: Primitive radius; server default: 1.0
    use_in_front: Draw in front; server default: False
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    """
    _payload = {"type": type, "name": name, "radius": radius, "use_in_front": use_in_front, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("geometry.create_grease_pencil", _drop_none(_payload))


def create_metaball(_session, *, type=None, name=None, radius=None, location=None, rotation=None, scale=None):
    """Create a metaball primitive

    Parameters (omit to use the server default):
    type: Metaball primitive type; server default: 'BALL'
    name: Optional object name; server default: ''
    radius: Primitive radius; server default: 1.0
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    """
    _payload = {"type": type, "name": name, "radius": radius, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("geometry.create_metaball", _drop_none(_payload))


def create_surface(_session, *, type=None, name=None, radius=None, location=None, rotation=None, scale=None):
    """Create a NURBS surface primitive

    Parameters (omit to use the server default):
    type: Surface primitive type
    name: Optional object name; server default: ''
    radius: Primitive radius; server default: 1.0
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    """
    _payload = {"type": type, "name": name, "radius": radius, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("geometry.create_surface", _drop_none(_payload))


def create_text(_session, *, name=None, body=None, align_x=None, align_y=None, size=None, location=None, rotation=None, scale=None):
    """Create a text object

    Parameters (omit to use the server default):
    name: Optional object name; server default: ''
    body: Text body; server default: 'Text'
    align_x: Horizontal alignment; server default: 'LEFT'
    align_y: Vertical alignment; server default: 'TOP_BASELINE'
    size: Text size; server default: 1.0
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    """
    _payload = {"name": name, "body": body, "align_x": align_x, "align_y": align_y, "size": size, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("geometry.create_text", _drop_none(_payload))


def report(_session, *, object=None):
    """Report non-mesh geometry object data

    Parameters (omit to use the server default):
    object: Object name
    """
    _payload = {"object": object}
    return _session.call("geometry.report", _drop_none(_payload))


def set_curve(_session, *, object=None, bevel_depth=None, bevel_resolution=None, extrude=None, resolution_u=None, render_resolution_u=None, dimensions=None, fill_mode=None, use_fill_caps=None):
    """Set curve-like geometry data fields

    Parameters (omit to use the server default):
    object: Object name
    bevel_depth: Bevel depth
    bevel_resolution: Bevel resolution
    extrude: Extrude amount
    resolution_u: Viewport resolution
    render_resolution_u: Render resolution
    dimensions: Curve dimensions
    fill_mode: Fill mode
    use_fill_caps: Fill bevel caps
    """
    _payload = {"object": object, "bevel_depth": bevel_depth, "bevel_resolution": bevel_resolution, "extrude": extrude, "resolution_u": resolution_u, "render_resolution_u": render_resolution_u, "dimensions": dimensions, "fill_mode": fill_mode, "use_fill_caps": use_fill_caps}
    return _session.call("geometry.set_curve", _drop_none(_payload))


def set_text(_session, *, object=None, body=None, align_x=None, align_y=None, size=None, space_line=None, offset_x=None, offset_y=None):
    """Set text object fields

    Parameters (omit to use the server default):
    object: Text object name
    body: Text body
    align_x: Horizontal alignment
    align_y: Vertical alignment
    size: Text size
    space_line: Line spacing
    offset_x: Horizontal text offset
    offset_y: Vertical text offset
    """
    _payload = {"object": object, "body": body, "align_x": align_x, "align_y": align_y, "size": size, "space_line": space_line, "offset_x": offset_x, "offset_y": offset_y}
    return _session.call("geometry.set_text", _drop_none(_payload))
