# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the info domain."""

from ..session import _drop_none


def messages(_session, *, limit=None):
    """Return Info editor report messages when exposed by Blender RNA

    Parameters (omit to use the server default):
    limit: Maximum messages to return; server default: 100
    """
    _payload = {"limit": limit}
    return _session.call("info.messages", _drop_none(_payload))


def report(_session):
    """Report Info editor areas and available report operators
    """
    return _session.call("info.report", {})
