# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the io domain."""

from ..session import _drop_none


def export(_session, *, path=None, format=None, objects=None, apply_modifiers=None, y_up=None):
    """Export the scene or selected objects; format can be inferred from the path

    Parameters (omit to use the server default):
    path: Output path
    format: AUTO infers from extension; otherwise GLB, GLTF_SEPARATE, FBX, or OBJ; server default: 'AUTO'
    objects: Comma-separated object names to export; default = whole scene
    apply_modifiers: Apply modifiers where supported; server default: True
    y_up: +Y up axis for formats that support it; server default: True
    """
    _payload = {"path": path, "format": format, "objects": objects, "apply_modifiers": apply_modifiers, "y_up": y_up}
    return _session.call("io.export", _drop_none(_payload))


def import_(_session, *, path=None, format=None):
    """Import a mesh/scene file; format inferred from the extension by default

    Parameters (omit to use the server default):
    path: Absolute path to the file to import
    format: Importer to use; AUTO infers it from the file extension; server default: 'AUTO'
    """
    _payload = {"path": path, "format": format}
    return _session.call("io.import", _drop_none(_payload))

globals()['import'] = import_


def prepare_asset(_session, *, object=None, path=None, format=None, apply_transforms=None, apply_modifiers=None, y_up=None):
    """Optionally apply transforms on one object, then export just that object

    Parameters (omit to use the server default):
    object: Object to prepare
    path: Output path
    format: AUTO infers from extension; otherwise GLB, GLTF_SEPARATE, FBX, or OBJ; server default: 'AUTO'
    apply_transforms: Apply location/rotation/scale before export; server default: True
    apply_modifiers: Apply modifiers where supported; server default: True
    y_up: +Y up axis for formats that support it; server default: True
    """
    _payload = {"object": object, "path": path, "format": format, "apply_transforms": apply_transforms, "apply_modifiers": apply_modifiers, "y_up": y_up}
    return _session.call("io.prepare_asset", _drop_none(_payload))


def profile_validate(_session, *, object=None, profile=None, format=None, y_up=None, allowed_formats=None, require_collision=None, min_lods=None, require_applied_transforms=None, name_regex=None):
    """Validate an object against a parameterized export profile without exporting

    Parameters (omit to use the server default):
    object: Object to validate
    profile: Export convention profile; server default: 'GENERIC'
    format: Planned export format; server default: 'GLB'
    y_up: Planned +Y-up export option
    allowed_formats: CUSTOM override: comma-separated allowed formats; server default: ''
    require_collision: CUSTOM override: require a collision proxy; server default: False
    min_lods: CUSTOM override: minimum detected LOD variants; server default: 0
    require_applied_transforms: CUSTOM override: require identity/applied transforms; server default: True
    name_regex: CUSTOM override: object-name regex; server default: ''
    """
    _payload = {"object": object, "profile": profile, "format": format, "y_up": y_up, "allowed_formats": allowed_formats, "require_collision": require_collision, "min_lods": min_lods, "require_applied_transforms": require_applied_transforms, "name_regex": name_regex}
    return _session.call("io.profile_validate", _drop_none(_payload))
