# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the lattice domain."""

from ..session import _drop_none


def convert_to_mesh(_session, *, object=None, name=None):
    """Convert a lattice to a mesh when Blender supports conversion

    Parameters (omit to use the server default):
    object: Lattice object to convert
    name: Optional converted object name; server default: ''
    """
    _payload = {"object": object, "name": name}
    return _session.call("lattice.convert_to_mesh", _drop_none(_payload))


def create(_session, *, name=None, location=None):
    """Create a lattice object

    Parameters (omit to use the server default):
    name: Optional object name; server default: ''
    location: World location; server default: [0, 0, 0]
    """
    _payload = {"name": name, "location": location}
    return _session.call("lattice.create", _drop_none(_payload))


def point_set(_session, *, object=None, index=None, co_deform=None):
    """Set one lattice point's deformed coordinate

    Parameters (omit to use the server default):
    object: Lattice object to edit
    index: Lattice point index
    co_deform: New deformed coordinate
    """
    _payload = {"object": object, "index": index, "co_deform": co_deform}
    return _session.call("lattice.point_set", _drop_none(_payload))


def report(_session, *, object=None):
    """Report lattice object, data, and point state

    Parameters (omit to use the server default):
    object: Lattice object to inspect
    """
    _payload = {"object": object}
    return _session.call("lattice.report", _drop_none(_payload))


def set(_session, *, object=None, property=None, value=None):
    """Set one RNA property on lattice data

    Parameters (omit to use the server default):
    object: Lattice object to edit
    property: Lattice data property
    value: New value as JSON
    """
    _payload = {"object": object, "property": property, "value": value}
    return _session.call("lattice.set", _drop_none(_payload))
