# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the lightprobe domain."""

from ..session import _drop_none


def create(_session, *, type=None, name=None, location=None):
    """Create a light probe object

    Parameters (omit to use the server default):
    type: Light probe type
    name: Optional object name; server default: ''
    location: World location; server default: [0, 0, 0]
    """
    _payload = {"type": type, "name": name, "location": location}
    return _session.call("lightprobe.create", _drop_none(_payload))


def list(_session):
    """List light probe objects
    """
    return _session.call("lightprobe.list", {})


def report(_session, *, name=None):
    """Report live RNA properties for a light probe

    Parameters (omit to use the server default):
    name: Light probe object name
    """
    _payload = {"name": name}
    return _session.call("lightprobe.report", _drop_none(_payload))


def set(_session, *, name=None, property=None, value=None):
    """Set one RNA property on a light probe data-block

    Parameters (omit to use the server default):
    name: Light probe object name
    property: Light probe data property
    value: New value as JSON
    """
    _payload = {"name": name, "property": property, "value": value}
    return _session.call("lightprobe.set", _drop_none(_payload))
