# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the light domain."""

from ..session import _drop_none


def create(_session, *, type=None, name=None, location=None, rotation=None, energy=None, color=None, size=None, spot_size=None, spot_blend=None):
    """Create a light object

    Parameters (omit to use the server default):
    type: Light type; server default: 'POINT'
    name: Optional light object name; server default: ''
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    energy: Light energy; server default: 10.0
    color: Light RGB color; server default: [1.0, 1.0, 1.0]
    size: Area/point light size
    spot_size: Spot cone angle in radians
    spot_blend: Spot edge softness
    """
    _payload = {"type": type, "name": name, "location": location, "rotation": rotation, "energy": energy, "color": color, "size": size, "spot_size": spot_size, "spot_blend": spot_blend}
    return _session.call("light.create", _drop_none(_payload))


def list(_session):
    """List scene lights
    """
    return _session.call("light.list", {})


def report(_session, *, light=None):
    """Report one light, or all scene lights if omitted

    Parameters (omit to use the server default):
    light: Light object name; server default: ''
    """
    _payload = {"light": light}
    return _session.call("light.report", _drop_none(_payload))


def set(_session, *, light=None, energy=None, color=None, size=None, spot_size=None, spot_blend=None):
    """Set common light data properties

    Parameters (omit to use the server default):
    light: Light object name
    energy: Light energy
    color: Light RGB color
    size: Area/point light size
    spot_size: Spot cone angle in radians
    spot_blend: Spot edge softness
    """
    _payload = {"light": light, "energy": energy, "color": color, "size": size, "spot_size": spot_size, "spot_blend": spot_blend}
    return _session.call("light.set", _drop_none(_payload))
