# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the mesh domain."""

from ..session import _drop_none


def bevel(_session, *, object=None, offset=None, segments=None):
    """Bevel the selected edges/vertices

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    offset: Bevel width; server default: 0.1
    segments: Number of bevel segments; server default: 1
    """
    _payload = {"object": object, "offset": offset, "segments": segments}
    return _session.call("mesh.bevel", _drop_none(_payload))


def delete(_session, *, object=None, type=None):
    """Delete selected mesh elements

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    type: Delete mode; server default: 'VERT'
    """
    _payload = {"object": object, "type": type}
    return _session.call("mesh.delete", _drop_none(_payload))


def dissolve(_session, *, object=None, type=None, use_verts=None, angle_limit=None, use_dissolve_boundaries=None):
    """Dissolve selected mesh elements

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    type: Dissolve mode; server default: 'EDGES'
    use_verts: Dissolve connected vertices for edges/faces; server default: False
    angle_limit: Limited dissolve angle in radians; server default: 0.0872665
    use_dissolve_boundaries: Dissolve boundaries in limited mode; server default: False
    """
    _payload = {"object": object, "type": type, "use_verts": use_verts, "angle_limit": angle_limit, "use_dissolve_boundaries": use_dissolve_boundaries}
    return _session.call("mesh.dissolve", _drop_none(_payload))


def edge_face_add(_session, *, object=None):
    """Create an edge or face from selected elements

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("mesh.edge_face_add", _drop_none(_payload))


def extrude(_session, *, object=None, translate=None):
    """Extrude the selected region and translate it

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    translate: Translation applied to the extruded region [x, y, z]
    """
    _payload = {"object": object, "translate": translate}
    return _session.call("mesh.extrude", _drop_none(_payload))


def fill(_session, *, object=None, beauty=None):
    """Fill selected edges

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    beauty: Use beauty fill; server default: True
    """
    _payload = {"object": object, "beauty": beauty}
    return _session.call("mesh.fill", _drop_none(_payload))


def inset(_session, *, object=None, thickness=None):
    """Inset the selected faces

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    thickness: Inset thickness; server default: 0.1
    """
    _payload = {"object": object, "thickness": thickness}
    return _session.call("mesh.inset", _drop_none(_payload))


def merge(_session, *, object=None, type=None, uvs=None):
    """Merge selected vertices

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    type: Merge mode; server default: 'CENTER'
    uvs: Merge UVs; server default: True
    """
    _payload = {"object": object, "type": type, "uvs": uvs}
    return _session.call("mesh.merge", _drop_none(_payload))


def quads_to_tris(_session, *, object=None, quad_method=None, ngon_method=None):
    """Convert selected faces to triangles

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    quad_method: Quad split method; server default: 'BEAUTY'
    ngon_method: N-gon triangulation method; server default: 'BEAUTY'
    """
    _payload = {"object": object, "quad_method": quad_method, "ngon_method": ngon_method}
    return _session.call("mesh.quads_to_tris", _drop_none(_payload))


def recalc_normals(_session, *, object=None, inside=None):
    """Recalculate the mesh normals consistently

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    inside: Point normals inside instead of outside; server default: False
    """
    _payload = {"object": object, "inside": inside}
    return _session.call("mesh.recalc_normals", _drop_none(_payload))


def remove_doubles(_session, *, object=None, threshold=None):
    """Merge duplicate vertices

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    threshold: Merge distance threshold; server default: 0.0001
    """
    _payload = {"object": object, "threshold": threshold}
    return _session.call("mesh.remove_doubles", _drop_none(_payload))


def report(_session, *, object=None):
    """Analytic topology report for a mesh (read-only)

    Parameters (omit to use the server default):
    object: Mesh object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("mesh.report", _drop_none(_payload))


def select_all(_session, *, object=None, action=None):
    """Select, deselect, invert, or toggle all mesh elements

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    action: Select-all action; server default: 'SELECT'
    """
    _payload = {"object": object, "action": action}
    return _session.call("mesh.select_all", _drop_none(_payload))


def select_by_index(_session, *, object=None, mode=None, indices=None, action=None):
    """Select mesh elements by zero-based index

    Parameters (omit to use the server default):
    object: Mesh object to edit
    mode: Element mode
    indices: Comma-separated element indices
    action: Selection action; server default: 'REPLACE'
    """
    _payload = {"object": object, "mode": mode, "indices": indices, "action": action}
    return _session.call("mesh.select_by_index", _drop_none(_payload))


def selection_report(_session, *, object=None):
    """Report selected vertices, edges, and faces

    Parameters (omit to use the server default):
    object: Mesh object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("mesh.selection_report", _drop_none(_payload))


def shade_smooth(_session, *, object=None, smooth=None):
    """Toggle smooth/flat shading on the object

    Parameters (omit to use the server default):
    object: Mesh object to shade (defaults to active)
    smooth: Smooth shading when true, flat when false; server default: True
    """
    _payload = {"object": object, "smooth": smooth}
    return _session.call("mesh.shade_smooth", _drop_none(_payload))


def subdivide(_session, *, object=None, cuts=None):
    """Subdivide the selected edges/faces

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    cuts: Number of cuts; server default: 1
    """
    _payload = {"object": object, "cuts": cuts}
    return _session.call("mesh.subdivide", _drop_none(_payload))


def tris_to_quads(_session, *, object=None, face_threshold=None, shape_threshold=None):
    """Convert selected triangles to quads

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    face_threshold: Face angle in degrees; server default: 40.0
    shape_threshold: Shape angle in degrees; server default: 40.0
    """
    _payload = {"object": object, "face_threshold": face_threshold, "shape_threshold": shape_threshold}
    return _session.call("mesh.tris_to_quads", _drop_none(_payload))
