# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the modifiers domain."""

from ..session import _drop_none


def add(_session, *, object=None, type=None, name=None):
    """Add a modifier to an object's stack

    Parameters (omit to use the server default):
    object: Object to modify (defaults to active)
    type: Modifier type to add, e.g. SUBSURF or NODES
    name: Name for the new modifier (defaults to the type label)
    """
    _payload = {"object": object, "type": type, "name": name}
    return _session.call("modifiers.add", _drop_none(_payload))


def apply(_session, *, object=None, name=None):
    """Apply (bake) a modifier into the mesh

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to apply
    """
    _payload = {"object": object, "name": name}
    return _session.call("modifiers.apply", _drop_none(_payload))


def copy(_session, *, object=None, name=None, new_name=None):
    """Copy a modifier in the stack

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to copy
    new_name: Optional name for the copied modifier; server default: ''
    """
    _payload = {"object": object, "name": name, "new_name": new_name}
    return _session.call("modifiers.copy", _drop_none(_payload))


def list(_session, *, object=None):
    """List the modifier stack of an object (read-only)

    Parameters (omit to use the server default):
    object: Object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("modifiers.list", _drop_none(_payload))


def move(_session, *, object=None, name=None, index=None):
    """Move a modifier to a stack index

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to move
    index: Destination stack index
    """
    _payload = {"object": object, "name": name, "index": index}
    return _session.call("modifiers.move", _drop_none(_payload))


def remove(_session, *, object=None, name=None):
    """Remove a modifier from the stack without applying it

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to remove
    """
    _payload = {"object": object, "name": name}
    return _session.call("modifiers.remove", _drop_none(_payload))


def set(_session, *, object=None, name=None, property=None, value=None):
    """Set a property on an existing modifier

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to edit
    property: Modifier property to set (e.g. 'levels', 'thickness')
    value: New value (coerced to the property's type)
    """
    _payload = {"object": object, "name": name, "property": property, "value": value}
    return _session.call("modifiers.set", _drop_none(_payload))


def set_visibility(_session, *, object=None, name=None, viewport=None, render=None, editmode=None, cage=None, expanded=None):
    """Set common modifier stack visibility flags

    Parameters (omit to use the server default):
    object: Object owning the modifier (defaults to active)
    name: Name of the modifier to edit
    viewport: Show modifier in viewport
    render: Show modifier in renders
    editmode: Show modifier in edit mode
    cage: Show modifier on cage
    expanded: Show modifier panel expanded
    """
    _payload = {"object": object, "name": name, "viewport": viewport, "render": render, "editmode": editmode, "cage": cage, "expanded": expanded}
    return _session.call("modifiers.set_visibility", _drop_none(_payload))


def types(_session):
    """List modifier types supported by the running Blender
    """
    return _session.call("modifiers.types", {})
