# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the object domain."""

from ..session import _drop_none


def bake_transfer(_session, *, source=None, target=None, maps=None, size=None, ray_distance=None):
    """Bake high->low detail (normal/AO) from a source mesh into a target mesh's maps

    Parameters (omit to use the server default):
    source: High-poly source object
    target: Low-poly target object (must have UVs)
    maps: Comma-separated maps to bake: NORMAL, AO; server default: 'NORMAL,AO'
    size: Baked image size in pixels; server default: 1024
    ray_distance: Cage extrusion / ray distance; server default: 0.01
    """
    _payload = {"source": source, "target": target, "maps": maps, "size": size, "ray_distance": ray_distance}
    return _session.call("object.bake_transfer", _drop_none(_payload))


def bounds(_session, *, object=None):
    """Read an object's local and world bounds

    Parameters (omit to use the server default):
    object: Object name
    """
    _payload = {"object": object}
    return _session.call("object.bounds", _drop_none(_payload))


def collision_hulls_create(_session, *, object=None, name_prefix=None, count=None, axis=None, margin=None):
    """Create split box collision hulls across an object's bounds using generic Asset_COL_## names

    Parameters (omit to use the server default):
    object: Source object to bound
    name_prefix: Optional proxy prefix; default is <object>_COL; server default: ''
    count: Number of hull boxes to create; server default: 2
    axis: Axis used to split the bounds; server default: 'LONGEST'
    margin: Extra size added around each hull; server default: 0.0
    """
    _payload = {"object": object, "name_prefix": name_prefix, "count": count, "axis": axis, "margin": margin}
    return _session.call("object.collision_hulls_create", _drop_none(_payload))


def collision_proxy_create(_session, *, object=None, name=None, shape=None, margin=None):
    """Create a simple collision proxy around an object's bounds using a generic Asset_COL naming convention

    Parameters (omit to use the server default):
    object: Source object to bound
    name: Optional proxy name; default is <object>_COL; server default: ''
    shape: Proxy shape; server default: 'BOX'
    margin: Extra size added around the source bounds; server default: 0.0
    """
    _payload = {"object": object, "name": name, "shape": shape, "margin": margin}
    return _session.call("object.collision_proxy_create", _drop_none(_payload))


def create(_session, *, type=None, name=None, location=None, rotation=None, scale=None, size=None, radius=None, vertices=None, depth=None, radius1=None, radius2=None, major_radius=None, minor_radius=None, major_segments=None, minor_segments=None, end_fill_type=None, calc_uvs=None, empty_display_type=None):
    """Create a common mesh primitive or empty

    Parameters (omit to use the server default):
    type: Object primitive type
    name: Optional object name; server default: ''
    location: World location [x, y, z]; server default: [0.0, 0.0, 0.0]
    rotation: Euler rotation in radians [x, y, z]; server default: [0.0, 0.0, 0.0]
    scale: Scale [x, y, z]; server default: [1.0, 1.0, 1.0]
    size: Size for cube, plane, monkey; server default: 2.0
    radius: Radius for sphere or empty display; server default: 1.0
    vertices: Vertices for cylinder/cone/sphere; server default: 32
    depth: Depth for cylinder/cone; server default: 2.0
    radius1: Cone base radius; server default: 1.0
    radius2: Cone top radius; server default: 0.0
    major_radius: Torus major radius; server default: 1.0
    minor_radius: Torus minor radius; server default: 0.25
    major_segments: Torus major segments; server default: 48
    minor_segments: Torus minor segments; server default: 12
    end_fill_type: Cylinder/cone cap fill; server default: 'NGON'
    calc_uvs: Generate primitive UVs when supported; server default: True
    empty_display_type: Empty display type; server default: 'PLAIN_AXES'
    """
    _payload = {"type": type, "name": name, "location": location, "rotation": rotation, "scale": scale, "size": size, "radius": radius, "vertices": vertices, "depth": depth, "radius1": radius1, "radius2": radius2, "major_radius": major_radius, "minor_radius": minor_radius, "major_segments": major_segments, "minor_segments": minor_segments, "end_fill_type": end_fill_type, "calc_uvs": calc_uvs, "empty_display_type": empty_display_type}
    return _session.call("object.create", _drop_none(_payload))


def delete(_session, *, objects=None):
    """Delete one or more objects

    Parameters (omit to use the server default):
    objects: Comma-separated object names
    """
    _payload = {"objects": objects}
    return _session.call("object.delete", _drop_none(_payload))


def duplicate(_session, *, object=None, name=None, linked=None, offset=None):
    """Duplicate an object

    Parameters (omit to use the server default):
    object: Object name
    name: Optional duplicate name; server default: ''
    linked: Share source object data; server default: False
    offset: Location offset [x, y, z]; server default: [0.0, 0.0, 0.0]
    """
    _payload = {"object": object, "name": name, "linked": linked, "offset": offset}
    return _session.call("object.duplicate", _drop_none(_payload))


def lod_create(_session, *, object=None, name=None, level=None, ratio=None, apply=None):
    """Create a decimated LOD duplicate using a generic Asset_LOD# naming convention

    Parameters (omit to use the server default):
    object: Source mesh object
    name: Optional LOD object name; default is <object>_LOD<level>; server default: ''
    level: LOD level number; server default: 1
    ratio: Decimate ratio for the LOD mesh; server default: 0.5
    apply: Apply the decimate modifier immediately; server default: False
    """
    _payload = {"object": object, "name": name, "level": level, "ratio": ratio, "apply": apply}
    return _session.call("object.lod_create", _drop_none(_payload))


def origin_set(_session, *, object=None, type=None, center=None):
    """Set an object's origin

    Parameters (omit to use the server default):
    object: Object name
    type: Origin operation; server default: 'ORIGIN_GEOMETRY'
    center: Origin center mode; server default: 'MEDIAN'
    """
    _payload = {"object": object, "type": type, "center": center}
    return _session.call("object.origin_set", _drop_none(_payload))


def rename(_session, *, object=None, name=None):
    """Rename an object

    Parameters (omit to use the server default):
    object: Object name
    name: New object name
    """
    _payload = {"object": object, "name": name}
    return _session.call("object.rename", _drop_none(_payload))


def retopo(_session, *, object=None, target_faces=None, voxel_size=None, adaptivity=None, preserve_sharp=None, preserve_boundary=None):
    """Retopologize a mesh to clean quads at a face budget (voxel remesh -> quadriflow)

    Parameters (omit to use the server default):
    object: Mesh object to retopologize
    target_faces: Target quad face count
    voxel_size: Voxel size for the cleanup pass; 0 = auto from bbox; server default: 0.0
    adaptivity: Voxel adaptivity (0 = uniform); server default: 0.0
    preserve_sharp: Preserve sharp edges in quadriflow; server default: True
    preserve_boundary: Preserve open boundaries in quadriflow; server default: True
    """
    _payload = {"object": object, "target_faces": target_faces, "voxel_size": voxel_size, "adaptivity": adaptivity, "preserve_sharp": preserve_sharp, "preserve_boundary": preserve_boundary}
    return _session.call("object.retopo", _drop_none(_payload))


def transform_apply(_session, *, object=None, location=None, rotation=None, scale=None, properties=None, isolate_users=None):
    """Apply an object's transform

    Parameters (omit to use the server default):
    object: Object name
    location: Apply location; server default: True
    rotation: Apply rotation; server default: True
    scale: Apply scale; server default: True
    properties: Apply object data properties; server default: True
    isolate_users: Make shared data single-user first; server default: False
    """
    _payload = {"object": object, "location": location, "rotation": rotation, "scale": scale, "properties": properties, "isolate_users": isolate_users}
    return _session.call("object.transform_apply", _drop_none(_payload))


def transform_get(_session, *, object=None):
    """Read an object's transform state

    Parameters (omit to use the server default):
    object: Object name
    """
    _payload = {"object": object}
    return _session.call("object.transform_get", _drop_none(_payload))


def transform_set(_session, *, object=None, location=None, rotation=None, scale=None, delta_location=None, delta_rotation=None, delta_scale=None, rotation_mode=None):
    """Set an object's transform fields

    Parameters (omit to use the server default):
    object: Object name
    location: World location [x, y, z]
    rotation: Euler rotation in radians [x, y, z]
    scale: Scale [x, y, z]
    delta_location: Delta location [x, y, z]
    delta_rotation: Delta Euler rotation [x, y, z]
    delta_scale: Delta scale [x, y, z]
    rotation_mode: Euler rotation mode
    """
    _payload = {"object": object, "location": location, "rotation": rotation, "scale": scale, "delta_location": delta_location, "delta_rotation": delta_rotation, "delta_scale": delta_scale, "rotation_mode": rotation_mode}
    return _session.call("object.transform_set", _drop_none(_payload))
