# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the outliner domain."""

from ..session import _drop_none


def collection_create(_session, *, name=None, parent=None):
    """Create a collection under the scene root or a named parent collection

    Parameters (omit to use the server default):
    name: New collection name
    parent: Parent collection; scene root when empty; server default: ''
    """
    _payload = {"name": name, "parent": parent}
    return _session.call("outliner.collection_create", _drop_none(_payload))


def collection_delete(_session, *, collection=None, force=None):
    """Delete a collection; force is required when it contains objects or child collections

    Parameters (omit to use the server default):
    collection: Collection to delete
    force: Allow deleting a non-empty collection; server default: False
    """
    _payload = {"collection": collection, "force": force}
    return _session.call("outliner.collection_delete", _drop_none(_payload))


def collection_rename(_session, *, collection=None, name=None):
    """Rename a collection

    Parameters (omit to use the server default):
    collection: Collection to rename
    name: New collection name
    """
    _payload = {"collection": collection, "name": name}
    return _session.call("outliner.collection_rename", _drop_none(_payload))


def collection_visibility_set(_session, *, collection=None, viewport=None, render=None, selectable=None):
    """Set collection-level viewport/render/selectability restrictions

    Parameters (omit to use the server default):
    collection: Collection to update
    viewport: Visible in viewport
    render: Renderable
    selectable: Selectable
    """
    _payload = {"collection": collection, "viewport": viewport, "render": render, "selectable": selectable}
    return _session.call("outliner.collection_visibility_set", _drop_none(_payload))


def describe(_session, *, target=None, kind=None):
    """Describe one object, collection, scene, or view layer by name

    Parameters (omit to use the server default):
    target: Name to describe
    kind: Restrict the lookup to one datablock kind (AUTO tries each in turn); server default: 'AUTO'
    """
    _payload = {"target": target, "kind": kind}
    return _session.call("outliner.describe", _drop_none(_payload))


def find(_session, *, query=None, kind=None, limit=None):
    """Search objects, collections, scenes, and view layers by name

    Parameters (omit to use the server default):
    query: Case-insensitive name substring
    kind: Restrict result kind; server default: 'ANY'
    limit: Maximum matches; server default: 50
    """
    _payload = {"query": query, "kind": kind, "limit": limit}
    return _session.call("outliner.find", _drop_none(_payload))


def layer_collection_set(_session, *, view_layer=None, collection=None, exclude=None, viewport=None, holdout=None, indirect_only=None):
    """Set view-layer collection restrictions for one collection

    Parameters (omit to use the server default):
    view_layer: View layer name
    collection: Collection in the view-layer tree
    exclude: Exclude collection from this view layer
    viewport: Visible in this view layer
    holdout: Holdout in this view layer
    indirect_only: Indirect-only in this view layer
    """
    _payload = {"view_layer": view_layer, "collection": collection, "exclude": exclude, "viewport": viewport, "holdout": holdout, "indirect_only": indirect_only}
    return _session.call("outliner.layer_collection_set", _drop_none(_payload))


def object_link(_session, *, object=None, collection=None):
    """Link an object into a collection without removing existing collection membership

    Parameters (omit to use the server default):
    object: Object to link
    collection: Target collection
    """
    _payload = {"object": object, "collection": collection}
    return _session.call("outliner.object_link", _drop_none(_payload))


def object_move(_session, *, object=None, collection=None):
    """Move an object to exactly one target collection

    Parameters (omit to use the server default):
    object: Object to move
    collection: Target collection
    """
    _payload = {"object": object, "collection": collection}
    return _session.call("outliner.object_move", _drop_none(_payload))


def object_unlink(_session, *, object=None, collection=None, force=None):
    """Unlink an object from a collection; force is required if it is the final collection

    Parameters (omit to use the server default):
    object: Object to unlink
    collection: Collection to unlink from
    force: Allow object to have no collection users; server default: False
    """
    _payload = {"object": object, "collection": collection, "force": force}
    return _session.call("outliner.object_unlink", _drop_none(_payload))


def orphans(_session):
    """List zero-user datablocks in high-value Outliner categories
    """
    return _session.call("outliner.orphans", {})


def orphans_purge(_session, *, force=None):
    """Purge orphan datablocks; force is always required

    Parameters (omit to use the server default):
    force: Confirm orphan purge; server default: False
    """
    _payload = {"force": force}
    return _session.call("outliner.orphans_purge", _drop_none(_payload))


def parent_clear(_session, *, object=None, keep_transform=None):
    """Clear an object's parent, preserving world transform by default

    Parameters (omit to use the server default):
    object: Object to unparent
    keep_transform: Preserve world transform; server default: True
    """
    _payload = {"object": object, "keep_transform": keep_transform}
    return _session.call("outliner.parent_clear", _drop_none(_payload))


def parent_set(_session, *, object=None, parent=None, keep_transform=None):
    """Set an object's parent, preserving world transform by default

    Parameters (omit to use the server default):
    object: Child object
    parent: Parent object
    keep_transform: Preserve world transform; server default: True
    """
    _payload = {"object": object, "parent": parent, "keep_transform": keep_transform}
    return _session.call("outliner.parent_set", _drop_none(_payload))


def tree(_session):
    """Return the logical scene tree: scenes, view layers, collections, objects, and hierarchy
    """
    return _session.call("outliner.tree", {})


def view_layer_create(_session, *, name=None):
    """Create a view layer

    Parameters (omit to use the server default):
    name: New view layer name
    """
    _payload = {"name": name}
    return _session.call("outliner.view_layer_create", _drop_none(_payload))


def view_layer_delete(_session, *, name=None, force=None):
    """Delete a view layer; force is required and the last layer cannot be deleted

    Parameters (omit to use the server default):
    name: View layer to delete
    force: Confirm render organization change; server default: False
    """
    _payload = {"name": name, "force": force}
    return _session.call("outliner.view_layer_delete", _drop_none(_payload))


def view_layers(_session):
    """List view layers and their layer-collection restriction trees
    """
    return _session.call("outliner.view_layers", {})


def visibility_set(_session, *, object=None, viewport=None, render=None, selectable=None):
    """Set object-level viewport/render/selectability restrictions

    Parameters (omit to use the server default):
    object: Object to update
    viewport: Visible in viewport
    render: Renderable
    selectable: Selectable
    """
    _payload = {"object": object, "viewport": viewport, "render": render, "selectable": selectable}
    return _session.call("outliner.visibility_set", _drop_none(_payload))
