# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the particles domain."""

from ..session import _drop_none


def add(_session, *, object=None, name=None):
    """Add a particle system to an object

    Parameters (omit to use the server default):
    object: Object to edit
    name: Optional particle system name; server default: ''
    """
    _payload = {"object": object, "name": name}
    return _session.call("particles.add", _drop_none(_payload))


def remove(_session, *, object=None, name=None):
    """Remove a named particle system from an object

    Parameters (omit to use the server default):
    object: Object to edit
    name: Particle system name
    """
    _payload = {"object": object, "name": name}
    return _session.call("particles.remove", _drop_none(_payload))


def report(_session, *, object=None, name=None):
    """Report live RNA properties for one or all particle systems

    Parameters (omit to use the server default):
    object: Object to inspect
    name: Optional particle system name; omit for all; server default: ''
    """
    _payload = {"object": object, "name": name}
    return _session.call("particles.report", _drop_none(_payload))


def set(_session, *, object=None, name=None, property=None, value=None):
    """Set one RNA property on a particle system or its settings

    Parameters (omit to use the server default):
    object: Object to edit
    name: Particle system name
    property: Property path, e.g. count or settings.frame_start
    value: New value as JSON
    """
    _payload = {"object": object, "name": name, "property": property, "value": value}
    return _session.call("particles.set", _drop_none(_payload))


def systems(_session, *, object=None):
    """List particle systems on an object

    Parameters (omit to use the server default):
    object: Object to inspect
    """
    _payload = {"object": object}
    return _session.call("particles.systems", _drop_none(_payload))
