# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the physics domain."""

from ..session import _drop_none


def add(_session, *, object=None, type=None):
    """Add a physics stack to an object

    Parameters (omit to use the server default):
    object: Object to edit
    type: Physics stack type
    """
    _payload = {"object": object, "type": type}
    return _session.call("physics.add", _drop_none(_payload))


def field_report(_session, *, object=None):
    """Report an object's force field settings

    Parameters (omit to use the server default):
    object: Object to inspect
    """
    _payload = {"object": object}
    return _session.call("physics.field_report", _drop_none(_payload))


def field_set(_session, *, object=None, property=None, value=None):
    """Set one RNA property on an object's force field

    Parameters (omit to use the server default):
    object: Object to edit
    property: Force field RNA property identifier
    value: New value as JSON
    """
    _payload = {"object": object, "property": property, "value": value}
    return _session.call("physics.field_set", _drop_none(_payload))


def remove(_session, *, object=None, type=None):
    """Remove a physics stack from an object

    Parameters (omit to use the server default):
    object: Object to edit
    type: Physics stack type
    """
    _payload = {"object": object, "type": type}
    return _session.call("physics.remove", _drop_none(_payload))


def report(_session, *, object=None):
    """Report all physics stacks on an object

    Parameters (omit to use the server default):
    object: Object to inspect
    """
    _payload = {"object": object}
    return _session.call("physics.report", _drop_none(_payload))


def set(_session, *, object=None, type=None, property=None, value=None):
    """Set one RNA property on a physics stack

    Parameters (omit to use the server default):
    object: Object to edit
    type: Physics stack type
    property: RNA property path, e.g. mass or settings.quality
    value: New value as JSON
    """
    _payload = {"object": object, "type": type, "property": property, "value": value}
    return _session.call("physics.set", _drop_none(_payload))
