# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the pointcloud domain."""

from ..session import _drop_none


def attributes(_session, *, name_or_object=None):
    """List point cloud geometry attributes and color attributes

    Parameters (omit to use the server default):
    name_or_object: Point cloud object or data-block name
    """
    _payload = {"name_or_object": name_or_object}
    return _session.call("pointcloud.attributes", _drop_none(_payload))


def list(_session):
    """List point cloud objects and data-blocks
    """
    return _session.call("pointcloud.list", {})


def report(_session, *, name_or_object=None):
    """Report live RNA properties for a point cloud

    Parameters (omit to use the server default):
    name_or_object: Point cloud object or data-block name
    """
    _payload = {"name_or_object": name_or_object}
    return _session.call("pointcloud.report", _drop_none(_payload))


def set(_session, *, name_or_object=None, property=None, value=None):
    """Set one writable RNA property on a point cloud data-block

    Parameters (omit to use the server default):
    name_or_object: Point cloud object or data-block name
    property: PointCloud data property
    value: New value as JSON
    """
    _payload = {"name_or_object": name_or_object, "property": property, "value": value}
    return _session.call("pointcloud.set", _drop_none(_payload))
