# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the project domain."""

from ..session import _drop_none


def files(_session):
    """List files for the active or detected Blender project
    """
    return _session.call("project.files", {})


def report(_session):
    """Report active or detected Blender project state and project editor areas
    """
    return _session.call("project.report", {})


def settings(_session):
    """Report project preferences, active project fields, and project.toml data
    """
    return _session.call("project.settings", {})
