# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the properties domain."""

from ..session import _drop_none


def get(_session, *, path=None):
    """Read a stable Properties path such as object:Cube/location or object:Cube/idprops/foo

    Parameters (omit to use the server default):
    path: Stable path, with path segments percent-encoded if needed
    """
    _payload = {"path": path}
    return _session.call("properties.get", _drop_none(_payload))


def object_report(_session, *, object=None, include_data=None, include_modifiers=None, include_values=None):
    """Report all live RNA properties for an object, its data, modifiers, and custom props

    Parameters (omit to use the server default):
    object: Object name
    include_data: Include object.data RNA properties; server default: True
    include_modifiers: Include modifier RNA properties; server default: True
    include_values: Include current property values when readable; server default: True
    """
    _payload = {"object": object, "include_data": include_data, "include_modifiers": include_modifiers, "include_values": include_values}
    return _session.call("properties.object_report", _drop_none(_payload))


def report(_session, *, path=None, include_values=None):
    """Report all live RNA properties for any stable Properties path target

    Parameters (omit to use the server default):
    path: Stable root path, e.g. object:Cube or data:meshes/CubeMesh
    include_values: Include current property values when readable; server default: True
    """
    _payload = {"path": path, "include_values": include_values}
    return _session.call("properties.report", _drop_none(_payload))


def set(_session, *, path=None, value=None):
    """Set a stable Properties path; value is JSON-encoded

    Parameters (omit to use the server default):
    path: Stable path to a mutable RNA or custom property
    value: New value as a JSON string
    """
    _payload = {"path": path, "value": value}
    return _session.call("properties.set", _drop_none(_payload))


def unset(_session, *, path=None):
    """Unset a custom property or resettable RNA property by stable Properties path

    Parameters (omit to use the server default):
    path: Stable path to remove or reset
    """
    _payload = {"path": path}
    return _session.call("properties.unset", _drop_none(_payload))
