# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the render domain."""

from ..session import _drop_none


def set_settings(_session, *, engine=None, filepath=None, resolution_x=None, resolution_y=None, image_format=None, transparent=None):
    """Set common render settings

    Parameters (omit to use the server default):
    engine: Render engine
    filepath: Render output path
    resolution_x: Render width in pixels
    resolution_y: Render height in pixels
    image_format: Render image format
    transparent: Film transparent
    """
    _payload = {"engine": engine, "filepath": filepath, "resolution_x": resolution_x, "resolution_y": resolution_y, "image_format": image_format, "transparent": transparent}
    return _session.call("render.set_settings", _drop_none(_payload))


def settings(_session):
    """Report active render settings
    """
    return _session.call("render.settings", {})


def still(_session, *, path=None, camera=None, engine=None, resolution_x=None, resolution_y=None, image_format=None):
    """Render a still image to disk, restoring prior scene settings after

    Parameters (omit to use the server default):
    path: Destination image path
    camera: Camera object to use for this render; server default: ''
    engine: Temporary render engine
    resolution_x: Temporary render width
    resolution_y: Temporary render height
    image_format: Temporary image format; server default: 'PNG'
    """
    _payload = {"path": path, "camera": camera, "engine": engine, "resolution_x": resolution_x, "resolution_y": resolution_y, "image_format": image_format}
    return _session.call("render.still", _drop_none(_payload))
