# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the rig domain."""

from ..session import _drop_none


def add_armature(_session, *, name=None, location=None):
    """Create a new armature (skeleton) object

    Parameters (omit to use the server default):
    name: Name for the new armature object
    location: World location of the armature [x, y, z]
    """
    _payload = {"name": name, "location": location}
    return _session.call("rig.add_armature", _drop_none(_payload))


def add_bone(_session, *, armature=None, name=None, head=None, tail=None):
    """Add an edit bone to an armature (head/tail in armature-local space)

    Parameters (omit to use the server default):
    armature: Armature object to add the bone to
    name: Name for the new bone
    head: Bone head position [x, y, z] (defaults to origin)
    tail: Bone tail position [x, y, z] (defaults to +Z unit)
    """
    _payload = {"armature": armature, "name": name, "head": head, "tail": tail}
    return _session.call("rig.add_bone", _drop_none(_payload))


def assign_weights(_session, *, mesh=None, group=None, vertices=None, weight=None, mode=None):
    """Assign vertex weights to a named vertex group by vertex index

    Parameters (omit to use the server default):
    mesh: Mesh object to edit
    group: Vertex group name
    vertices: Comma-separated vertex indices
    weight: Weight to assign; server default: 1.0
    mode: Blender vertex group assignment mode; server default: 'REPLACE'
    """
    _payload = {"mesh": mesh, "group": group, "vertices": vertices, "weight": weight, "mode": mode}
    return _session.call("rig.assign_weights", _drop_none(_payload))


def clear_pose(_session, *, armature=None):
    """Clear all pose bone transforms back to rest values

    Parameters (omit to use the server default):
    armature: Armature object whose pose to clear
    """
    _payload = {"armature": armature}
    return _session.call("rig.clear_pose", _drop_none(_payload))


def constraint_add(_session, *, armature=None, bone=None, type=None, name=None, target=None, subtarget=None, influence=None):
    """Add a pose bone constraint

    Parameters (omit to use the server default):
    armature: Armature object owning the pose bone
    bone: Pose bone to edit
    type: Blender constraint type, e.g. COPY_LOCATION or IK
    name: Optional constraint name
    target: Optional target object name
    subtarget: Optional target bone/subtarget name
    influence: Constraint influence; server default: 1.0
    """
    _payload = {"armature": armature, "bone": bone, "type": type, "name": name, "target": target, "subtarget": subtarget, "influence": influence}
    return _session.call("rig.constraint_add", _drop_none(_payload))


def constraint_remove(_session, *, armature=None, bone=None, name=None):
    """Remove a named pose bone constraint

    Parameters (omit to use the server default):
    armature: Armature object owning the pose bone
    bone: Pose bone to edit
    name: Constraint name to remove
    """
    _payload = {"armature": armature, "bone": bone, "name": name}
    return _session.call("rig.constraint_remove", _drop_none(_payload))


def constraints(_session, *, armature=None, bone=None):
    """List pose bone constraints on one bone or the whole armature

    Parameters (omit to use the server default):
    armature: Armature object to inspect
    bone: Optional pose bone name to inspect
    """
    _payload = {"armature": armature, "bone": bone}
    return _session.call("rig.constraints", _drop_none(_payload))


def list_bones(_session, *, armature=None):
    """List an armature's bones with head/tail positions (read-only)

    Parameters (omit to use the server default):
    armature: Armature object to inspect
    """
    _payload = {"armature": armature}
    return _session.call("rig.list_bones", _drop_none(_payload))


def parent_with_auto_weights(_session, *, mesh=None, armature=None):
    """Parent a mesh to an armature with automatic skinning weights

    Parameters (omit to use the server default):
    mesh: Mesh object to skin
    armature: Armature object to bind the mesh to
    """
    _payload = {"mesh": mesh, "armature": armature}
    return _session.call("rig.parent_with_auto_weights", _drop_none(_payload))


def pose_report(_session, *, armature=None, bone=None):
    """Report pose bone transforms and constraints

    Parameters (omit to use the server default):
    armature: Armature object to inspect
    bone: Optional pose bone name to inspect
    """
    _payload = {"armature": armature, "bone": bone}
    return _session.call("rig.pose_report", _drop_none(_payload))


def report(_session, *, armature=None):
    """Report rest bones, pose bones, constraints, and child meshes

    Parameters (omit to use the server default):
    armature: Armature object to inspect
    """
    _payload = {"armature": armature}
    return _session.call("rig.report", _drop_none(_payload))


def set_bone_transform(_session, *, armature=None, bone=None, head=None, tail=None):
    """Set an existing bone's head and/or tail position

    Parameters (omit to use the server default):
    armature: Armature object owning the bone
    bone: Name of the bone to move
    head: New bone head position [x, y, z]
    tail: New bone tail position [x, y, z]
    """
    _payload = {"armature": armature, "bone": bone, "head": head, "tail": tail}
    return _session.call("rig.set_bone_transform", _drop_none(_payload))


def set_pose_bone(_session, *, armature=None, bone=None, location=None, rotation=None, scale=None, rotation_mode=None):
    """Set a pose bone's location, Euler rotation, and/or scale

    Parameters (omit to use the server default):
    armature: Armature object owning the pose bone
    bone: Pose bone to edit
    location: Pose bone location [x, y, z]
    rotation: Euler rotation in radians [x, y, z]
    scale: Pose bone scale [x, y, z]
    rotation_mode: Euler rotation mode; defaults to XYZ when rotation is provided
    """
    _payload = {"armature": armature, "bone": bone, "location": location, "rotation": rotation, "scale": scale, "rotation_mode": rotation_mode}
    return _session.call("rig.set_pose_bone", _drop_none(_payload))


def vertex_group_create(_session, *, mesh=None, name=None):
    """Create a mesh vertex group

    Parameters (omit to use the server default):
    mesh: Mesh object to edit
    name: Vertex group name
    """
    _payload = {"mesh": mesh, "name": name}
    return _session.call("rig.vertex_group_create", _drop_none(_payload))


def vertex_groups(_session, *, mesh=None):
    """List mesh vertex groups and assigned vertex weights

    Parameters (omit to use the server default):
    mesh: Mesh object to inspect
    """
    _payload = {"mesh": mesh}
    return _session.call("rig.vertex_groups", _drop_none(_payload))
