# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the rna domain."""

from ..session import _drop_none


def call_operator(_session, *, idname=None, args=None, object=None, mode=None, select=None):
    """Run any bpy.ops operator, with args validated against its RNA

    Parameters (omit to use the server default):
    idname: Operator id, e.g. 'mesh.bevel' or 'object.shade_smooth'
    args: Operator arguments as a JSON object string, e.g. '{"offset": 0.2}'
    object: Active object name to set before running (optional)
    mode: Interaction mode, e.g. 'EDIT' / 'OBJECT' (optional)
    select: Object names to select as a JSON array string, e.g. '["Cube"]'
    """
    _payload = {"idname": idname, "args": args, "object": object, "mode": mode, "select": select}
    return _session.call("rna.call_operator", _drop_none(_payload))


def describe(_session, *, path=None):
    """Describe a Blender operator or type via RNA (e.g. 'op:mesh.bevel', 'type:Object')

    Parameters (omit to use the server default):
    path: 'op:<cat>.<name>' or 'type:<TypeName>'
    """
    _payload = {"path": path}
    return _session.call("rna.describe", _drop_none(_payload))


def get_property(_session, *, path=None):
    """Read a data property by path under bpy.data (read-only)

    Parameters (omit to use the server default):
    path: Dotted path under bpy.data, e.g. 'objects.Cube.location'
    """
    _payload = {"path": path}
    return _session.call("rna.get_property", _drop_none(_payload))


def search(_session, *, query=None, kind=None, category=None, limit=None):
    """Search the live Blender API for operators/types matching a query, ranked by relevance

    Parameters (omit to use the server default):
    query: Substring to match against idname/label/description (e.g. 'bevel', 'subdivide')
    kind: Restrict results to operators, types, or both; server default: 'any'
    category: Optional operator category to scope to (e.g. 'mesh', 'object')
    limit: Max number of matches to return; server default: 30
    """
    _payload = {"query": query, "kind": kind, "category": category, "limit": limit}
    return _session.call("rna.search", _drop_none(_payload))


def set_property(_session, *, path=None, value=None):
    """Set a data property by path under bpy.data (value is JSON-encoded)

    Parameters (omit to use the server default):
    path: Dotted path under bpy.data, e.g. 'objects.Cube.location'
    value: New value as a JSON string, e.g. '[1, 2, 3]' or '0.5' or '"NAME"'
    """
    _payload = {"path": path, "value": value}
    return _session.call("rna.set_property", _drop_none(_payload))
