# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the scene domain."""

from ..session import _drop_none


def create_object(_session, *, type=None, name=None, location=None):
    """Create a primitive object in the scene

    Parameters (omit to use the server default):
    type: Primitive type
    name: Optional object name
    location: World location [x, y, z]
    """
    _payload = {"type": type, "name": name, "location": location}
    return _session.call("scene.create_object", _drop_none(_payload))


def info(_session):
    """Summarize the current scene (objects, materials)
    """
    return _session.call("scene.info", {})


def set_transform(_session, *, object=None, location=None, rotation=None, scale=None):
    """Set an object's location/rotation/scale

    Parameters (omit to use the server default):
    object: Object name
    location: World location [x, y, z]
    rotation: Euler rotation in radians [x, y, z]
    scale: Scale [x, y, z]
    """
    _payload = {"object": object, "location": location, "rotation": rotation, "scale": scale}
    return _session.call("scene.set_transform", _drop_none(_payload))
