# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the script domain."""

from ..session import _drop_none


def paths(_session):
    """List Blender script search paths and configured script directories
    """
    return _session.call("script.paths", {})


def reload(_session):
    """Reload Blender scripts when Python execution is trusted
    """
    return _session.call("script.reload", {})


def report(_session):
    """Report script-space operators, preferences, paths, and editor areas
    """
    return _session.call("script.report", {})


def run_file(_session, *, path=None):
    """Run a Python file through Blender's script operator when Python execution is trusted

    Parameters (omit to use the server default):
    path: Python file path
    """
    _payload = {"path": path}
    return _session.call("script.run_file", _drop_none(_payload))
