# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the sequencer domain."""

from ..session import _drop_none


def modifier_add(_session, *, name=None, type=None, modifier_name=None):
    """Add a strip modifier to a sequence strip

    Parameters (omit to use the server default):
    name: Strip name
    type: Modifier type, e.g. BRIGHT_CONTRAST
    modifier_name: Optional modifier name; server default: ''
    """
    _payload = {"name": name, "type": type, "modifier_name": modifier_name}
    return _session.call("sequencer.modifier_add", _drop_none(_payload))


def modifier_remove(_session, *, name=None, modifier=None):
    """Remove a strip modifier

    Parameters (omit to use the server default):
    name: Strip name
    modifier: Modifier name
    """
    _payload = {"name": name, "modifier": modifier}
    return _session.call("sequencer.modifier_remove", _drop_none(_payload))


def modifier_set(_session, *, name=None, modifier=None, property=None, value=None):
    """Set one RNA property on a strip modifier

    Parameters (omit to use the server default):
    name: Strip name
    modifier: Modifier name
    property: Modifier RNA property identifier
    value: New value as JSON
    """
    _payload = {"name": name, "modifier": modifier, "property": property, "value": value}
    return _session.call("sequencer.modifier_set", _drop_none(_payload))


def modifiers(_session, *, name=None):
    """List strip modifiers on a sequence strip

    Parameters (omit to use the server default):
    name: Strip name
    """
    _payload = {"name": name}
    return _session.call("sequencer.modifiers", _drop_none(_payload))


def report(_session):
    """Report sequence strips in the active scene
    """
    return _session.call("sequencer.report", {})


def strip_add(_session, *, type=None, name=None, frame_start=None, channel=None, path=None):
    """Add a sequence strip

    Parameters (omit to use the server default):
    type: Strip type, e.g. COLOR, TEXT, MOVIE, SOUND
    name: Optional strip name; server default: ''
    frame_start: Start frame; server default: 1
    channel: Sequencer channel; server default: 1
    path: File path for movie or sound strips; server default: ''
    """
    _payload = {"type": type, "name": name, "frame_start": frame_start, "channel": channel, "path": path}
    return _session.call("sequencer.strip_add", _drop_none(_payload))


def strip_remove(_session, *, name=None):
    """Remove a sequence strip by name

    Parameters (omit to use the server default):
    name: Strip name
    """
    _payload = {"name": name}
    return _session.call("sequencer.strip_remove", _drop_none(_payload))


def strip_set(_session, *, name=None, property=None, value=None):
    """Set one RNA property on a sequence strip

    Parameters (omit to use the server default):
    name: Strip name
    property: Strip RNA property identifier
    value: New value as JSON
    """
    _payload = {"name": name, "property": property, "value": value}
    return _session.call("sequencer.strip_set", _drop_none(_payload))
