# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the session domain."""

from ..session import _drop_none


def checkpoint(_session, *, object=None, label=None):
    """Snapshot an object's mesh data + transform so an edit can be rolled back

    Parameters (omit to use the server default):
    object: Object to snapshot (defaults to active)
    label: Checkpoint label (auto-generated if omitted)
    """
    _payload = {"object": object, "label": label}
    return _session.call("session.checkpoint", _drop_none(_payload))


def list_checkpoints(_session, *, object=None):
    """List stored checkpoints for an object, or all objects (read-only)

    Parameters (omit to use the server default):
    object: Object to list checkpoints for (all objects if omitted)
    """
    _payload = {"object": object}
    return _session.call("session.list_checkpoints", _drop_none(_payload))


def revert(_session, *, object=None, label=None):
    """Restore an object from a checkpoint (most recent if no label); one undo step

    Parameters (omit to use the server default):
    object: Object to restore (defaults to active)
    label: Checkpoint label to restore (defaults to most recent)
    """
    _payload = {"object": object, "label": label}
    return _session.call("session.revert", _drop_none(_payload))
