# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the shading domain."""

from ..session import _drop_none


def add_image_texture(_session, *, material=None, image_path=None, target=None):
    """Wire an image-texture node to a Principled BSDF target

    Parameters (omit to use the server default):
    material: Material to edit
    image_path: Filesystem path to the image to load
    target: Principled input to drive: BASE_COLOR, ROUGHNESS or NORMAL; server default: 'BASE_COLOR'
    """
    _payload = {"material": material, "image_path": image_path, "target": target}
    return _session.call("shading.add_image_texture", _drop_none(_payload))


def add_node(_session, *, material=None, type=None, name=None):
    """Add a shader node to a material node tree

    Parameters (omit to use the server default):
    material: Material to edit
    type: Shader node bl_idname, e.g. ShaderNodeTexNoise
    name: Optional node name; server default: ''
    """
    _payload = {"material": material, "type": type, "name": name}
    return _session.call("shading.add_node", _drop_none(_payload))


def assign_material(_session, *, object=None, material=None):
    """Assign a material to an object (creates it if missing)

    Parameters (omit to use the server default):
    object: Object to receive the material
    material: Material name (created if it does not exist)
    """
    _payload = {"object": object, "material": material}
    return _session.call("shading.assign_material", _drop_none(_payload))


def create_material(_session, *, name=None):
    """Create a new node-based material

    Parameters (omit to use the server default):
    name: Optional material name
    """
    _payload = {"name": name}
    return _session.call("shading.create_material", _drop_none(_payload))


def link_nodes(_session, *, material=None, from_node=None, from_socket=None, to_node=None, to_socket=None):
    """Link two shader node sockets

    Parameters (omit to use the server default):
    material: Material to edit
    from_node: Source node name
    from_socket: Source output socket name or index
    to_node: Destination node name
    to_socket: Destination input socket name or index
    """
    _payload = {"material": material, "from_node": from_node, "from_socket": from_socket, "to_node": to_node, "to_socket": to_socket}
    return _session.call("shading.link_nodes", _drop_none(_payload))


def list_materials(_session, *, object=None):
    """List materials in the file (read-only)

    Parameters (omit to use the server default):
    object: Limit to one object's material slots
    """
    _payload = {"object": object}
    return _session.call("shading.list_materials", _drop_none(_payload))


def prepare_pbr_maps(_session, *, object=None, material=None, prefix=None, maps=None, size=None):
    """Create node-based PBR image slots for BASE_COLOR, NORMAL, ROUGHNESS, AO, and CAVITY

    Parameters (omit to use the server default):
    object: Object to receive or reuse the material
    material: Material to create/reuse; default is object's active material or <object>_PBR; server default: ''
    prefix: Image name prefix; default is object or material name; server default: ''
    maps: Comma-separated map set; default is BASE_COLOR,NORMAL,ROUGHNESS,AO,CAVITY; server default: ''
    size: Square image size in pixels; server default: 1024
    """
    _payload = {"object": object, "material": material, "prefix": prefix, "maps": maps, "size": size}
    return _session.call("shading.prepare_pbr_maps", _drop_none(_payload))


def report(_session, *, material=None, object=None):
    """Report a material, object material slots, and shader node tree

    Parameters (omit to use the server default):
    material: Material name; server default: ''
    object: Object whose active material and slots should be reported; server default: ''
    """
    _payload = {"material": material, "object": object}
    return _session.call("shading.report", _drop_none(_payload))


def set_node_input(_session, *, material=None, node=None, input=None, value=None):
    """Set a shader node input default value from JSON

    Parameters (omit to use the server default):
    material: Material to edit
    node: Node name
    input: Input socket name or index
    value: JSON scalar or array value
    """
    _payload = {"material": material, "node": node, "input": input, "value": value}
    return _session.call("shading.set_node_input", _drop_none(_payload))


def set_principled(_session, *, material=None, object=None, base_color=None, alpha=None, metallic=None, roughness=None, emission_strength=None):
    """Set Principled BSDF parameters on a material

    Parameters (omit to use the server default):
    material: Material name (else resolved from 'object')
    object: Object whose active material to edit (if no 'material')
    base_color: Base color RGB [r, g, b], each 0..1
    alpha: Alpha (opacity) 0..1
    metallic: Metallic 0..1
    roughness: Roughness 0..1
    emission_strength: Emission strength
    """
    _payload = {"material": material, "object": object, "base_color": base_color, "alpha": alpha, "metallic": metallic, "roughness": roughness, "emission_strength": emission_strength}
    return _session.call("shading.set_principled", _drop_none(_payload))
