# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the shaderfx domain."""

from ..session import _drop_none


def add(_session, *, object=None, type=None, name=None):
    """Add a shader effect to a Grease Pencil object's stack

    Parameters (omit to use the server default):
    object: Object to edit
    type: Shader effect type, e.g. FX_BLUR
    name: Optional shader effect name; server default: ''
    """
    _payload = {"object": object, "type": type, "name": name}
    return _session.call("shaderfx.add", _drop_none(_payload))


def list(_session, *, object=None):
    """List shader effects on a Grease Pencil object

    Parameters (omit to use the server default):
    object: Object to inspect
    """
    _payload = {"object": object}
    return _session.call("shaderfx.list", _drop_none(_payload))


def remove(_session, *, object=None, name=None):
    """Remove a named shader effect

    Parameters (omit to use the server default):
    object: Object to edit
    name: Shader effect name
    """
    _payload = {"object": object, "name": name}
    return _session.call("shaderfx.remove", _drop_none(_payload))


def report(_session, *, object=None, name=None):
    """Report live RNA properties for one or all shader effects

    Parameters (omit to use the server default):
    object: Object to inspect
    name: Optional shader effect name; omit for all; server default: ''
    """
    _payload = {"object": object, "name": name}
    return _session.call("shaderfx.report", _drop_none(_payload))


def set(_session, *, object=None, name=None, property=None, value=None):
    """Set one RNA property on a shader effect

    Parameters (omit to use the server default):
    object: Object to edit
    name: Shader effect name
    property: Shader effect RNA property identifier
    value: New value as JSON
    """
    _payload = {"object": object, "name": name, "property": property, "value": value}
    return _session.call("shaderfx.set", _drop_none(_payload))


def types(_session):
    """List shader effect types supported by the running Blender
    """
    return _session.call("shaderfx.types", {})
