# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the speaker domain."""

from ..session import _drop_none


def create(_session, *, name=None, location=None):
    """Create a speaker object

    Parameters (omit to use the server default):
    name: Optional object name; server default: ''
    location: World location; server default: [0, 0, 0]
    """
    _payload = {"name": name, "location": location}
    return _session.call("speaker.create", _drop_none(_payload))


def list(_session):
    """List speaker objects
    """
    return _session.call("speaker.list", {})


def report(_session, *, name=None):
    """Report live RNA properties for a speaker

    Parameters (omit to use the server default):
    name: Speaker object name
    """
    _payload = {"name": name}
    return _session.call("speaker.report", _drop_none(_payload))


def set(_session, *, name=None, property=None, value=None):
    """Set one writable RNA property on a speaker data-block

    Parameters (omit to use the server default):
    name: Speaker object name
    property: Speaker data property
    value: New value as JSON
    """
    _payload = {"name": name, "property": property, "value": value}
    return _session.call("speaker.set", _drop_none(_payload))
