# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the spreadsheet domain."""

from ..session import _drop_none


def columns(_session, *, object=None, component=None):
    """List spreadsheet columns derived from object geometry attributes

    Parameters (omit to use the server default):
    object: Object name; defaults to the active object; server default: ''
    component: Geometry domain/component: POINT, EDGE, FACE, or CORNER; server default: ''
    """
    _payload = {"object": object, "component": component}
    return _session.call("spreadsheet.columns", _drop_none(_payload))


def report(_session, *, object=None, component=None):
    """Report spreadsheet editor state and object table shape

    Parameters (omit to use the server default):
    object: Object name; defaults to the active object; server default: ''
    component: Geometry domain/component: POINT, EDGE, FACE, or CORNER; server default: ''
    """
    _payload = {"object": object, "component": component}
    return _session.call("spreadsheet.report", _drop_none(_payload))


def rows(_session, *, object=None, component=None, limit=None, offset=None):
    """Return paginated spreadsheet rows derived from object geometry attributes

    Parameters (omit to use the server default):
    object: Object name; defaults to the active object; server default: ''
    component: Geometry domain/component: POINT, EDGE, FACE, or CORNER; server default: ''
    limit: Maximum rows to return; server default: 100
    offset: Row offset; server default: 0
    """
    _payload = {"object": object, "component": component, "limit": limit, "offset": offset}
    return _session.call("spreadsheet.rows", _drop_none(_payload))
