# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the statusbar domain."""

from ..session import _drop_none


def report(_session):
    """Report Status Bar context and scene statistics
    """
    return _session.call("statusbar.report", {})
