# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the system domain."""

from ..session import _drop_none


def cancel(_session, *, op_id=None):
    """Request cooperative cancellation of a queued/running operation (takes effect at the operation's next check), by id from system.operations

    Parameters (omit to use the server default):
    op_id: Operation id, e.g. 'op-7'
    """
    _payload = {"op_id": op_id}
    return _session.call("system.cancel", _drop_none(_payload))


def execute_python(_session, *, code=None):
    """Run Python inside Blender (disabled unless explicitly enabled)

    Parameters (omit to use the server default):
    code: Python source to exec
    """
    _payload = {"code": code}
    return _session.call("system.execute_python", _drop_none(_payload))


def health(_session):
    """Bridge health: Blender version, open .blend, queue depth, last-error ring buffer
    """
    return _session.call("system.health", {})


def operations(_session):
    """List in-flight and recent operations with progress (works even while the main thread is busy)
    """
    return _session.call("system.operations", {})
