# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the textures domain."""

from ..session import _drop_none


def list(_session):
    """List image datablocks
    """
    return _session.call("textures.list", {})


def load(_session, *, path=None, name=None):
    """Load an image datablock from disk

    Parameters (omit to use the server default):
    path: Filesystem path to the image
    name: Optional image datablock name; server default: ''
    """
    _payload = {"path": path, "name": name}
    return _session.call("textures.load", _drop_none(_payload))


def report(_session, *, name=None):
    """Report one image datablock

    Parameters (omit to use the server default):
    name: Image datablock name
    """
    _payload = {"name": name}
    return _session.call("textures.report", _drop_none(_payload))
