# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the text domain."""

from ..session import _drop_none


def append(_session, *, name=None, body=None):
    """Append to a Text data-block body

    Parameters (omit to use the server default):
    name: Text data-block name
    body: Text to append
    """
    _payload = {"name": name, "body": body}
    return _session.call("text.append", _drop_none(_payload))


def create(_session, *, name=None, body=None):
    """Create a Text data-block

    Parameters (omit to use the server default):
    name: Text data-block name
    body: Initial text body; server default: ''
    """
    _payload = {"name": name, "body": body}
    return _session.call("text.create", _drop_none(_payload))


def list(_session):
    """List Text data-blocks
    """
    return _session.call("text.list", {})


def open(_session, *, path=None, name=None):
    """Open a text file into a Text data-block

    Parameters (omit to use the server default):
    path: Text file path
    name: Optional data-block name; server default: ''
    """
    _payload = {"path": path, "name": name}
    return _session.call("text.open", _drop_none(_payload))


def read(_session, *, name=None):
    """Read a Text data-block

    Parameters (omit to use the server default):
    name: Text data-block name
    """
    _payload = {"name": name}
    return _session.call("text.read", _drop_none(_payload))


def remove(_session, *, name=None):
    """Remove a Text data-block

    Parameters (omit to use the server default):
    name: Text data-block name
    """
    _payload = {"name": name}
    return _session.call("text.remove", _drop_none(_payload))


def save(_session, *, name=None, path=None):
    """Save a Text data-block to disk

    Parameters (omit to use the server default):
    name: Text data-block name
    path: Optional save path; defaults to text.filepath; server default: ''
    """
    _payload = {"name": name, "path": path}
    return _session.call("text.save", _drop_none(_payload))


def write(_session, *, name=None, body=None):
    """Replace a Text data-block body

    Parameters (omit to use the server default):
    name: Text data-block name
    body: New text body
    """
    _payload = {"name": name, "body": body}
    return _session.call("text.write", _drop_none(_payload))
