# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the tool domain."""

from ..session import _drop_none


def active(_session, *, area_type=None, mode=None):
    """Report the active workspace tool for an editor/mode

    Parameters (omit to use the server default):
    area_type: Editor area type, e.g. VIEW_3D; server default: 'VIEW_3D'
    mode: Optional mode, e.g. OBJECT or EDIT_MESH; server default: ''
    """
    _payload = {"area_type": area_type, "mode": mode}
    return _session.call("tool.active", _drop_none(_payload))


def set(_session, *, idname=None, area_type=None, mode=None):
    """Switch the active workspace tool by idname

    Parameters (omit to use the server default):
    idname: Tool idname, e.g. builtin.move
    area_type: Editor area type, e.g. VIEW_3D; server default: 'VIEW_3D'
    mode: Optional mode, e.g. OBJECT or EDIT_MESH; server default: ''
    """
    _payload = {"idname": idname, "area_type": area_type, "mode": mode}
    return _session.call("tool.set", _drop_none(_payload))


def setting_get(_session, *, path=None):
    """Read one ToolSettings path

    Parameters (omit to use the server default):
    path: Dot path under bpy.context.tool_settings
    """
    _payload = {"path": path}
    return _session.call("tool.setting_get", _drop_none(_payload))


def setting_set(_session, *, path=None, value=None):
    """Set one ToolSettings path

    Parameters (omit to use the server default):
    path: Dot path under bpy.context.tool_settings
    value: New value as JSON
    """
    _payload = {"path": path, "value": value}
    return _session.call("tool.setting_set", _drop_none(_payload))


def settings(_session, *, area_type=None, mode=None):
    """Report active tool and live ToolSettings RNA properties

    Parameters (omit to use the server default):
    area_type: Editor area type, e.g. VIEW_3D; server default: 'VIEW_3D'
    mode: Optional mode, e.g. OBJECT or EDIT_MESH; server default: ''
    """
    _payload = {"area_type": area_type, "mode": mode}
    return _session.call("tool.settings", _drop_none(_payload))
