# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the topbar domain."""

from ..session import _drop_none


def command_search(_session, *, query=None, limit=None):
    """Search Blender commands exposed through bpy.ops without opening modal UI

    Parameters (omit to use the server default):
    query: Command search query; server default: ''
    limit: Maximum results to return; server default: 20
    """
    _payload = {"query": query, "limit": limit}
    return _session.call("topbar.command_search", _drop_none(_payload))


def report(_session):
    """Report active topbar context, workspace, scene, and search capability
    """
    return _session.call("topbar.report", {})
