# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the tracking domain."""

from ..session import _drop_none


def clip_load(_session, *, path=None, name=None):
    """Load a movie clip or image sequence source

    Parameters (omit to use the server default):
    path: Clip file path
    name: Optional clip name; server default: ''
    """
    _payload = {"path": path, "name": name}
    return _session.call("tracking.clip_load", _drop_none(_payload))


def clips(_session):
    """List loaded movie clips
    """
    return _session.call("tracking.clips", {})


def marker_report(_session, *, clip=None):
    """Report markers for each track in a clip

    Parameters (omit to use the server default):
    clip: MovieClip name
    """
    _payload = {"clip": clip}
    return _session.call("tracking.marker_report", _drop_none(_payload))


def report(_session):
    """Report MovieClip and tracking state
    """
    return _session.call("tracking.report", {})


def track_report(_session, *, clip=None):
    """Report tracks for a clip

    Parameters (omit to use the server default):
    clip: MovieClip name
    """
    _payload = {"clip": clip}
    return _session.call("tracking.track_report", _drop_none(_payload))
