# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the ui domain."""

from ..session import _drop_none


def operator_invoke(_session, *, idname=None, args=None, area=None, region=None, window_index=None, area_index=None, object=None, mode=None, select=None, require_area=None):
    """Run any Blender operator with explicit editor area context and undo-safe dispatch

    Parameters (omit to use the server default):
    idname: Operator id, e.g. mesh.bevel
    args: Operator arguments as a JSON object string
    area: Editor area type used for temp_override; server default: 'VIEW_3D'
    region: Region type inside the area; server default: 'WINDOW'
    window_index: Specific window index, or -1 for first match; server default: -1
    area_index: Specific area index, or -1 for first matching type; server default: -1
    object: Optional active object name
    mode: Optional interaction mode
    select: Selected object names as a JSON array string
    require_area: Fail if the target UI area is missing; server default: False
    """
    _payload = {"idname": idname, "args": args, "area": area, "region": region, "window_index": window_index, "area_index": area_index, "object": object, "mode": mode, "select": select, "require_area": require_area}
    return _session.call("ui.operator_invoke", _drop_none(_payload))


def operator_poll(_session, *, idname=None, area=None, region=None, window_index=None, area_index=None, object=None, mode=None, select=None, require_area=None):
    """Check whether a Blender operator polls in an explicit editor area context

    Parameters (omit to use the server default):
    idname: Operator id, e.g. mesh.bevel
    area: Editor area type used for temp_override; server default: 'VIEW_3D'
    region: Region type inside the area; server default: 'WINDOW'
    window_index: Specific window index, or -1 for first match; server default: -1
    area_index: Specific area index, or -1 for first matching type; server default: -1
    object: Optional active object name
    mode: Optional interaction mode
    select: Selected object names as a JSON array string
    require_area: Return unavailable if the target UI area is missing; server default: False
    """
    _payload = {"idname": idname, "area": area, "region": region, "window_index": window_index, "area_index": area_index, "object": object, "mode": mode, "select": select, "require_area": require_area}
    return _session.call("ui.operator_poll", _drop_none(_payload))


def redraw(_session, *, type=None, iterations=None):
    """Request a Blender UI redraw when wm.redraw_timer is available

    Parameters (omit to use the server default):
    type: Redraw timer type; server default: 'DRAW_WIN_SWAP'
    iterations: Number of redraw iterations; server default: 1
    """
    _payload = {"type": type, "iterations": iterations}
    return _session.call("ui.redraw", _drop_none(_payload))


def screenshot(_session, *, path=None, full=None):
    """Capture Blender's UI screenshot when screen.screenshot is available

    Parameters (omit to use the server default):
    path: Output screenshot path
    full: Capture the full Blender window when supported; server default: False
    """
    _payload = {"path": path, "full": full}
    return _session.call("ui.screenshot", _drop_none(_payload))


def state(_session):
    """Report Blender UI availability, active window, and foreground-only capability flags
    """
    return _session.call("ui.state", {})


def windows(_session):
    """List Blender windows, screens, workspaces, areas, regions, and UI geometry
    """
    return _session.call("ui.windows", {})
