# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the uv domain."""

from ..session import _drop_none


def average_islands_scale(_session, *, object=None):
    """Average the texel density / scale of all UV islands

    Parameters (omit to use the server default):
    object: Mesh object whose islands to scale (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("uv.average_islands_scale", _drop_none(_payload))


def cube_project(_session, *, object=None, cube_size=None):
    """Cube-project the selected faces onto the UV map

    Parameters (omit to use the server default):
    object: Mesh object to project (defaults to active)
    cube_size: Size of the projection cube; server default: 1.0
    """
    _payload = {"object": object, "cube_size": cube_size}
    return _session.call("uv.cube_project", _drop_none(_payload))


def export_layout(_session, *, object=None, path=None, size=None, opacity=None, export_all=None, modified=None, format=None):
    """Export the mesh UV layout as an image file

    Parameters (omit to use the server default):
    object: Mesh object to export (defaults to active)
    path: Destination image path
    size: Square output size in pixels; server default: 1024
    opacity: Face fill opacity; server default: 0.25
    export_all: Export all UVs, not just selected faces; server default: True
    modified: Export UVs after modifiers; server default: False
    format: Output file format; server default: 'AUTO'
    """
    _payload = {"object": object, "path": path, "size": size, "opacity": opacity, "export_all": export_all, "modified": modified, "format": format}
    return _session.call("uv.export_layout", _drop_none(_payload))


def layer_create(_session, *, object=None, name=None, do_init=None):
    """Create a UV layer

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    name: UV layer name; server default: 'UVMap'
    do_init: Initialize from existing UVs; server default: True
    """
    _payload = {"object": object, "name": name, "do_init": do_init}
    return _session.call("uv.layer_create", _drop_none(_payload))


def layer_delete(_session, *, object=None, name=None):
    """Delete a UV layer by name

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    name: UV layer name
    """
    _payload = {"object": object, "name": name}
    return _session.call("uv.layer_delete", _drop_none(_payload))


def layer_set_active(_session, *, object=None, name=None):
    """Set the active UV layer by name

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    name: UV layer name
    """
    _payload = {"object": object, "name": name}
    return _session.call("uv.layer_set_active", _drop_none(_payload))


def layers(_session, *, object=None):
    """List UV layers and active UV layer

    Parameters (omit to use the server default):
    object: Mesh object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("uv.layers", _drop_none(_payload))


def pack_islands(_session, *, object=None, margin=None):
    """Pack the UV islands to fit the [0,1] UV space

    Parameters (omit to use the server default):
    object: Mesh object whose islands to pack (defaults to active)
    margin: Space between packed islands in UV space; server default: 0.001
    """
    _payload = {"object": object, "margin": margin}
    return _session.call("uv.pack_islands", _drop_none(_payload))


def report(_session, *, object=None):
    """Analytic UV report for a mesh: layers, has_uvs, island count (read-only)

    Parameters (omit to use the server default):
    object: Mesh object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("uv.report", _drop_none(_payload))


def seams(_session, *, object=None):
    """Report seam edge indices

    Parameters (omit to use the server default):
    object: Mesh object to inspect (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("uv.seams", _drop_none(_payload))


def set_seams(_session, *, object=None, edges=None, action=None):
    """Set, add, remove, or clear seam edge flags

    Parameters (omit to use the server default):
    object: Mesh object to edit (defaults to active)
    edges: Comma-separated edge indices; server default: ''
    action: Seam mutation action; server default: 'SET'
    """
    _payload = {"object": object, "edges": edges, "action": action}
    return _session.call("uv.set_seams", _drop_none(_payload))


def smart_unwrap(_session, *, object=None, angle_limit=None, island_margin=None):
    """Smart UV project the selected faces (angle-based auto seams)

    Parameters (omit to use the server default):
    object: Mesh object to unwrap (defaults to active)
    angle_limit: Angle limit in degrees for splitting islands; server default: 66.0
    island_margin: Margin between islands in UV space; server default: 0.0
    """
    _payload = {"object": object, "angle_limit": angle_limit, "island_margin": island_margin}
    return _session.call("uv.smart_unwrap", _drop_none(_payload))


def sphere_project(_session, *, object=None):
    """Sphere-project the selected faces onto the UV map

    Parameters (omit to use the server default):
    object: Mesh object to project (defaults to active)
    """
    _payload = {"object": object}
    return _session.call("uv.sphere_project", _drop_none(_payload))


def unwrap(_session, *, object=None, method=None, island_margin=None):
    """Unwrap the selected faces along existing seams

    Parameters (omit to use the server default):
    object: Mesh object to unwrap (defaults to active)
    method: Unwrapping algorithm; server default: 'ANGLE_BASED'
    island_margin: Margin between islands in UV space; server default: 0.0
    """
    _payload = {"object": object, "method": method, "island_margin": island_margin}
    return _session.call("uv.unwrap", _drop_none(_payload))
