# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the volume domain."""

from ..session import _drop_none


def create_empty(_session, *, name=None, location=None):
    """Create an empty volume object

    Parameters (omit to use the server default):
    name: Optional object name; server default: ''
    location: World location; server default: [0, 0, 0]
    """
    _payload = {"name": name, "location": location}
    return _session.call("volume.create_empty", _drop_none(_payload))


def import_(_session, *, path=None, name=None):
    """Import an OpenVDB volume file

    Parameters (omit to use the server default):
    path: OpenVDB file path
    name: Optional object/data name; server default: ''
    """
    _payload = {"path": path, "name": name}
    return _session.call("volume.import", _drop_none(_payload))

globals()['import'] = import_


def list(_session):
    """List volume objects and data-blocks
    """
    return _session.call("volume.list", {})


def report(_session, *, name_or_object=None):
    """Report live RNA properties for a volume

    Parameters (omit to use the server default):
    name_or_object: Volume object or data-block name
    """
    _payload = {"name_or_object": name_or_object}
    return _session.call("volume.report", _drop_none(_payload))


def set(_session, *, name_or_object=None, property=None, value=None):
    """Set one writable RNA property on a volume data-block or nested settings object

    Parameters (omit to use the server default):
    name_or_object: Volume object or data-block name
    property: Volume property path, e.g. filepath or display.density
    value: New value as JSON
    """
    _payload = {"name_or_object": name_or_object, "property": property, "value": value}
    return _session.call("volume.set", _drop_none(_payload))
