# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.

"""Generated client functions for the world domain."""

from ..session import _drop_none


def report(_session):
    """Report scene world color and background strength
    """
    return _session.call("world.report", {})


def set(_session, *, color=None, strength=None):
    """Set scene world color and/or background strength

    Parameters (omit to use the server default):
    color: World RGB color
    strength: Background strength
    """
    _payload = {"color": color, "strength": strength}
    return _session.call("world.set", _drop_none(_payload))
