"""Generate a typed Python client SDK from the ToolSpec surface.

Each non-`generated`-tier spec becomes a function in its domain's module, e.g.
`mesh.tris_to_quads` -> client/tools/mesh.py:tris_to_quads. Functions default every
param to None and send only explicitly-passed args, so the server fills real defaults
(documented in the docstring). Deterministic: sorted domains, sorted tools, param order
follows ToolSpec.params insertion order.

Two keyword-collision edge cases the tool surface actually contains (neither is a param
collision, which is why they need separate handling from ``_arg_name``):

- Zero-param specs (47 of them, e.g. ``scene.info``) would otherwise render a bare
  trailing ``*`` with nothing after it (``def info(_session, *):``), which is a
  ``SyntaxError`` -- Python requires at least one keyword-only param after a bare
  ``*``. Fixed by only emitting ``*`` when there are params to follow it.
- Two tool names are themselves Python keywords (``io.import``, ``volume.import``), so
  ``def import(...):`` cannot be written at all. Fixed the same way ``_arg_name``
  handles keyword *params*: the function is defined under a trailing-underscore alias
  (``import_``) and then re-exposed under its real dotted-tool name via
  ``globals()["import"] = import_`` so ``getattr(module, "import")`` (used by
  ``session.<domain>.<tool>`` dispatch) still resolves.

Modules are grouped by the dotted-name prefix (``spec.name.partition(".")[0]``), not
``spec.category``. These agree for the great majority of tools (e.g. ``mesh.*`` has
category ``"mesh"``), but 29 curated specs across 4 categories name themselves with a
shorter/different prefix than their category: ``anim.*`` (category ``"animation"``),
``rig.*`` (category ``"rigging"``), and ``rna.*`` (split across categories
``"introspection"`` and ``"rna_exec"``, with no tool-name collision between them, so
both fold into one ``rna`` module). ``ToolSession.__getattr__`` and
``session.<domain>.<tool>()`` dispatch by the dotted-name prefix -- that's what
``session.anim.timeline(...)`` or ``session.rna.describe(...)`` calls resolve on the
wire (the actual bridge command is ``spec.command``, unaffected either way) -- so
grouping by ``category`` would produce a ``client/tools/animation.py`` that
``session.anim`` can never import. Grouping by prefix keeps generation and dispatch in
agreement.
"""

from __future__ import annotations

import keyword

from ..domains import build_router

_HEADER = "# GENERATED by client/generate.py from the ToolSpec surface — do not edit by hand.\n"


def _arg_name(pname: str) -> str:
    return f"{pname}_" if keyword.iskeyword(pname) else pname


def _tool_name(tool: str) -> str:
    return f"{tool}_" if keyword.iskeyword(tool) else tool


def _default_note(pname: str, param) -> str:
    d = getattr(param, "default", None)
    summ = (getattr(param, "summary", "") or "").strip()
    bits = []
    if summ:
        bits.append(summ)
    if d is not None:
        bits.append(f"server default: {d!r}")
    return f"    {pname}: {'; '.join(bits)}" if bits else f"    {pname}"


def _function_source(spec) -> str:
    _domain, _, tool = spec.name.partition(".")
    def_name = _tool_name(tool)
    params = list(spec.params.items())
    sig = ["_session"]
    if params:
        sig.append("*")
        sig.extend(f"{_arg_name(p)}=None" for p, _ in params)
    lines = [f"def {def_name}({', '.join(sig)}):"]
    doc = [f'    """{spec.summary}']
    if params:
        doc.append("")
        doc.append("    Parameters (omit to use the server default):")
        doc.extend(_default_note(p, pinfo) for p, pinfo in params)
    doc.append('    """')
    lines.extend(doc)
    if params:
        pairs = ", ".join(f'"{p}": {_arg_name(p)}' for p, _ in params)
        lines.append(f"    _payload = {{{pairs}}}")
        lines.append('    return _session.call("' + spec.command + '", _drop_none(_payload))')
    else:
        lines.append('    return _session.call("' + spec.command + '", {})')
    source = "\n".join(lines) + "\n"
    if def_name != tool:
        source += f"\nglobals()[{tool!r}] = {def_name}\n"
    return source


def generate_all() -> dict[str, str]:
    """Return {domain: module_source_text} for every non-generated-tier tool.

    Grouped by the dotted-name prefix (see module docstring) so the generated
    layout matches ``ToolSession`` dispatch, not by ``spec.category``.
    """
    by_domain: dict[str, list] = {}
    for spec in build_router().specs():
        if spec.tier == "generated":
            continue
        domain, _, _tool = spec.name.partition(".")
        by_domain.setdefault(domain, []).append(spec)
    out: dict[str, str] = {}
    for domain in sorted(by_domain):
        specs = sorted(by_domain[domain], key=lambda s: s.name)
        body = [
            _HEADER,
            '"""Generated client functions for the ' + domain + ' domain."""',
            "",
            "from ..session import _drop_none",
            "",
            "",
        ]
        body.append("\n\n".join(_function_source(s) for s in specs))
        out[domain] = "\n".join(body).rstrip("\n") + "\n"
    return out
